import { Lexicon } from './markup';
import type { LexEntry, SlotOption } from './types';

type Opts = { g?: boolean; rom?: string };
const w = (s: string, r: string, en: string, ar: string, o: Opts = {}): LexEntry => ({ s, r: r || undefined, en, ar, ...o });
const g = (s: string, en: string, ar: string, rom?: string): LexEntry => ({ s, en, ar, g: true, rom });

export const LEXICON_ENTRIES: LexEntry[] = [
  // ---- grammar ----
  g('は', 'topic marker', 'أداة الموضوع', 'wa'),
  g('が', 'subject marker', 'أداة الفاعل'),
  g('を', 'object marker', 'أداة المفعول به', 'o'),
  g('に', 'to / at (place, time)', 'إلى / في (مكان أو وقت)'),
  g('で', 'at / by / with', 'في / بـ / باستخدام'),
  g('の', "of / 's (possessive)", 'أداة الملكية'),
  g('へ', 'toward (direction)', 'نحو (اتجاه)', 'e'),
  g('と', 'and / with', 'و / مع'),
  g('も', 'also / too', 'أيضًا'),
  g('から', 'from', 'من'),
  g('か', 'question marker', 'أداة سؤال'),
  g('ね', '…, right? (asks for agreement)', '…، أليس كذلك؟'),
  g('です', 'is / am / are (polite)', 'يكون (صيغة مهذبة)'),
  g('ぐらい', 'about / approximately', 'حوالي / تقريبًا'),
  g('さん', 'Mr. / Ms. (polite title)', 'السيد / السيدة (لقب)'),

  // ---- greetings & set phrases ----
  w('いらっしゃいませ', '', 'welcome (said to customers)', 'أهلًا بك (يُقال للزبائن)'),
  w('いらっしゃい', '', 'welcome (casual)', 'أهلًا بك (بشكل ودّي)'),
  w('こんにちは', '', 'hello / good afternoon', 'مرحبًا / طاب يومك', { rom: 'konnichiwa' }),
  w('こんばんは', '', 'good evening', 'مساء الخير', { rom: 'konbanwa' }),
  w('おはようございます', '', 'good morning', 'صباح الخير', { rom: 'ohayō gozaimasu' }),
  w('はい', '', 'yes', 'نعم'),
  w('いいえ', '', 'no', 'لا'),
  w('わかりません', '', "I don't understand", 'لا أفهم'),
  w('すみません', '', 'excuse me / sorry', 'المعذرة / آسف'),
  w('ありがとう', '', 'thanks', 'شكرًا'),
  w('ありがとうございます', '', 'thank you', 'شكرًا جزيلًا', { rom: 'arigatō gozaimasu' }),
  w('ありがとうございました', '', 'thank you (for what you did)', 'شكرًا لك (بعد انتهاء الخدمة)', { rom: 'arigatō gozaimashita' }),
  w('どういたしまして', '', "you're welcome", 'عفوًا', { rom: 'dō itashimashite' }),
  w('お願いします', 'おねがいします', 'please (when asking)', 'من فضلك (عند الطلب)', { rom: 'onegai shimasu' }),
  w('ください', '', 'please give me', 'من فضلك أعطني'),
  w('どうぞ', '', 'please / go ahead / here you are', 'تفضّل'),
  w('はじめまして', '', 'nice to meet you', 'تشرفنا بمعرفتك'),
  w('わかりました', '', 'I understand / got it', 'فهمت'),
  w('いただきます', '', '(said before eating)', '(عبارة تُقال قبل الأكل)'),
  w('ごちそうさまでした', '', '(said after eating)', '(عبارة تُقال بعد الأكل لشكر المضيف)', { rom: 'gochisōsama deshita' }),
  w('お気をつけて', 'おきをつけて', 'take care', 'اعتنِ بنفسك', { rom: 'o-ki o tsukete' }),
  w('また', '', 'again / see you', 'مرة أخرى'),
  w('もう一度', 'もういちど', 'one more time', 'مرة أخرى'),
  w('ゆっくり', '', 'slowly', 'ببطء'),
  w('ちょっと', '', 'a little', 'قليلًا'),
  w('へい', '', '(a chef calling out "coming up!")', '(نداء ودّي من الطاهي)'),
  w('あ', '', 'oh', 'آه'),
  w('お待ち', 'おまち', 'thanks for waiting / here you go', 'شكرًا على الانتظار / تفضّل'),
  w('さようなら', '', 'goodbye', 'مع السلامة'),

  // ---- people ----
  w('わたし', '', 'I / me', 'أنا'),
  w('ミオ', '', 'Mio (a name)', 'ميو (اسم)'),
  w('大学生', 'だいがくせい', 'university student', 'طالب جامعي'),
  w('先生', 'せんせい', 'teacher', 'معلّم'),
  w('あなた', '', 'you', 'أنت'),
  w('お名前', 'おなまえ', 'your name (polite)', 'اسمك (بأدب)'),
  w('お元気', 'おげんき', 'well / healthy (polite)', 'بخير (بأدب)'),

  // ---- questions & demonstratives ----
  w('何', 'なに', 'what', 'ماذا'),
  w('何か', 'なにか', 'something / anything', 'شيء ما'),
  w('どこ', '', 'where', 'أين'),
  w('どれ', '', 'which one', 'أيّ واحد'),
  w('いくら', '', 'how much', 'بكم'),
  w('何分', 'なんぷん', 'how many minutes', 'كم دقيقة'),
  w('どうしましたか', '', "what's the matter? / how can I help?", 'ما الأمر؟ / كيف أساعدك؟', { rom: 'dō shimashita ka' }),
  w('これ', '', 'this', 'هذا'),
  w('あちら', '', 'over there (polite)', 'هناك (بأدب)'),
  w('あそこ', '', 'over there', 'هناك'),
  w('ほかに', '', 'anything else / in addition', 'شيئًا آخر / بالإضافة'),

  // ---- verbs & phrases ----
  w('あります', '', 'there is / I have', 'يوجد / لديّ'),
  w('いります', '', 'need', 'يحتاج'),
  w('いりません', '', "don't need", 'لا أحتاج'),
  w('行きたい', 'いきたい', 'want to go', 'أريد أن أذهب'),
  w('行きます', 'いきます', 'go', 'يذهب'),
  w('買います', 'かいます', 'buy', 'يشتري'),
  w('買えます', 'かえます', 'can buy', 'يمكن شراؤه'),
  w('乗ってください', 'のってください', 'please get on / take (a train)', 'من فضلك اركب'),
  w('来ました', 'きました', 'came', 'جئت'),
  w('かかります', '', 'it takes (time/money)', 'يستغرق'),
  w('します', '', 'do / will have', 'يفعل / سآخذ'),
  w('教えてください', 'おしえてください', 'please tell me', 'من فضلك أخبرني'),
  w('話しましょう', 'はなしましょう', "let's talk", 'لنتحدث'),
  w('言います', 'いいます', 'say', 'يقول'),
  w('大丈夫', 'だいじょうぶ', 'okay / fine', 'بخير / لا بأس'),
  w('好き', 'すき', 'like', 'أحب'),
  w('大好き', 'だいすき', 'love / really like', 'أحب كثيرًا'),
  w('辛い', 'からい', 'spicy', 'حار'),
  w('辛くない', 'からくない', 'not spicy', 'غير حار'),
  w('おいしい', '', 'delicious', 'لذيذ'),
  w('いい', '', 'good / nice', 'جيد'),
  w('どう', '', 'how', 'كيف'),
  w('とても', '', 'very', 'جدًا'),
  w('うれしい', '', 'happy / glad', 'سعيد'),
  w('元気', 'げんき', 'well / healthy', 'بخير'),

  // ---- shop & money ----
  w('ご注文', 'ごちゅうもん', 'order (polite)', 'الطلب'),
  w('全部で', 'ぜんぶで', 'in total', 'في المجموع'),
  w('四百五十円', 'よんひゃくごじゅうえん', '450 yen', '450 ين'),
  w('三百二十円', 'さんびゃくにじゅうえん', '320 yen', '320 ين'),
  w('百九十円', 'ひゃくきゅうじゅうえん', '190 yen', '190 ين'),
  w('九百円', 'きゅうひゃくえん', '900 yen', '900 ين'),
  w('二十分', 'にじゅっぷん', '20 minutes', '20 دقيقة'),
  w('三番線', 'さんばんせん', 'platform 3', 'الرصيف 3'),
  w('何番線', 'なんばんせん', 'which platform', 'أي رصيف'),
  w('現金', 'げんきん', 'cash', 'نقدًا'),
  w('カード', '', 'card', 'بطاقة'),
  w('袋', 'ふくろ', 'bag', 'كيس'),
  w('お会計', 'おかいけい', 'the bill', 'الحساب'),
  w('おすすめ', '', 'recommendation', 'ترشيح'),
  w('うち', '', 'our place / my home', 'محلّنا / بيتي'),
  w('パスワード', '', 'password', 'كلمة المرور'),
  w('Wi-Fi', 'わいふぁい', 'Wi-Fi', 'واي فاي'),
  w('ホット', '', 'hot', 'ساخن'),
  w('アイス', '', 'iced / cold', 'مثلّج / بارد'),

  // ---- food & drink ----
  w('コーヒー', '', 'coffee', 'قهوة'),
  w('紅茶', 'こうちゃ', 'black tea', 'شاي أسود'),
  w('お茶', 'おちゃ', 'green tea', 'شاي أخضر'),
  w('カフェラテ', '', 'café latte', 'كافيه لاتيه'),
  w('ジュース', '', 'juice', 'عصير'),
  w('水', 'みず', 'water', 'ماء'),
  w('牛乳', 'ぎゅうにゅう', 'milk', 'حليب'),
  w('おにぎり', '', 'rice ball', 'أونيغيري (كرة أرز)'),
  w('サンドイッチ', '', 'sandwich', 'ساندويتش'),
  w('お弁当', 'おべんとう', 'boxed lunch (bento)', 'وجبة غداء (بنتو)'),
  w('ケーキ', '', 'cake', 'كعكة'),
  w('ラーメン', '', 'ramen', 'رامن'),
  w('しょうゆ', '', 'soy sauce', 'صلصة الصويا'),
  w('みそ', '', 'miso', 'ميسو'),
  w('とんこつ', '', 'tonkotsu (pork-bone broth)', 'تونكوتسو (مرق عظام)'),

  // ---- places & transport ----
  w('トイレ', '', 'toilet', 'دورة المياه'),
  w('駅', 'えき', 'station', 'محطة'),
  w('渋谷', 'しぶや', 'Shibuya', 'شيبويا'),
  w('新宿', 'しんじゅく', 'Shinjuku', 'شينجوكو'),
  w('浅草', 'あさくさ', 'Asakusa', 'أساكوسا'),
  w('秋葉原', 'あきはばら', 'Akihabara', 'أكيهابارا'),
  w('上野', 'うえの', 'Ueno', 'أوينو'),
  w('東京', 'とうきょう', 'Tokyo', 'طوكيو'),
  w('東京駅', 'とうきょうえき', 'Tokyo Station', 'محطة طوكيو'),
  w('空港', 'くうこう', 'airport', 'مطار'),
  w('公園', 'こうえん', 'park', 'حديقة'),
  w('学校', 'がっこう', 'school', 'مدرسة'),
  w('コンビニ', '', 'convenience store', 'متجر صغير (كونبيني)'),
  w('カフェ', '', 'café', 'مقهى'),
  w('電車', 'でんしゃ', 'train', 'قطار'),
  w('切符', 'きっぷ', 'ticket', 'تذكرة'),
  w('機械', 'きかい', 'machine', 'آلة'),

  // ---- hobbies ----
  w('趣味', 'しゅみ', 'hobby', 'هواية'),
  w('アニメ', '', 'anime', 'أنمي'),
  w('漫画', 'まんが', 'manga', 'مانغا'),
  w('音楽', 'おんがく', 'music', 'موسيقى'),
  w('写真', 'しゃしん', 'photography', 'تصوير'),
  w('ゲーム', '', 'games', 'ألعاب'),
  w('スポーツ', '', 'sports', 'رياضة'),
  w('料理', 'りょうり', 'cooking', 'طبخ'),
  w('映画', 'えいが', 'movies', 'أفلام'),
  w('旅行', 'りょこう', 'travel', 'سفر'),
  w('本', 'ほん', 'books', 'كتب'),
  w('絵', 'え', 'drawing', 'رسم'),

  // ---- things you can tap in the city ----
  w('自動販売機', 'じどうはんばいき', 'vending machine', 'آلة بيع آلي'),
  w('桜', 'さくら', 'cherry blossom', 'زهر الكرز'),
  w('猫', 'ねこ', 'cat', 'قطة'),
  w('自転車', 'じてんしゃ', 'bicycle', 'دراجة'),
  w('信号', 'しんごう', 'traffic light', 'إشارة المرور'),
  w('出口', 'でぐち', 'exit', 'مخرج'),
  w('入口', 'いりぐち', 'entrance', 'مدخل'),
  w('池', 'いけ', 'pond', 'بركة'),
  w('鳥居', 'とりい', 'torii (shrine gate)', 'توري (بوابة المعبد)'),
  w('提灯', 'ちょうちん', 'paper lantern', 'فانوس ورقي'),
  w('ベンチ', '', 'bench', 'مقعد'),
  w('ポスト', '', 'mailbox', 'صندوق بريد'),
  w('券売機', 'けんばいき', 'ticket machine', 'آلة التذاكر'),
  w('ごみ箱', 'ごみばこ', 'trash can', 'سلة المهملات'),
  w('花', 'はな', 'flower', 'زهرة'),

  // ---- countries ----
  ...(
    [
      ['アメリカ', '', 'the United States', 'الولايات المتحدة'],
      ['イギリス', '', 'the United Kingdom', 'المملكة المتحدة'],
      ['カナダ', '', 'Canada', 'كندا'],
      ['オーストラリア', '', 'Australia', 'أستراليا'],
      ['エジプト', '', 'Egypt', 'مصر'],
      ['サウジアラビア', '', 'Saudi Arabia', 'السعودية'],
      ['ヨルダン', '', 'Jordan', 'الأردن'],
      ['レバノン', '', 'Lebanon', 'لبنان'],
      ['シリア', '', 'Syria', 'سوريا'],
      ['パレスチナ', '', 'Palestine', 'فلسطين'],
      ['イラク', '', 'Iraq', 'العراق'],
      ['モロッコ', '', 'Morocco', 'المغرب'],
      ['アルジェリア', '', 'Algeria', 'الجزائر'],
      ['チュニジア', '', 'Tunisia', 'تونس'],
      ['リビア', '', 'Libya', 'ليبيا'],
      ['スーダン', '', 'Sudan', 'السودان'],
      ['イエメン', '', 'Yemen', 'اليمن'],
      ['クウェート', '', 'Kuwait', 'الكويت'],
      ['カタール', '', 'Qatar', 'قطر'],
      ['オマーン', '', 'Oman', 'عُمان'],
      ['バーレーン', '', 'Bahrain', 'البحرين'],
      ['アラブ首長国連邦', 'あらぶしゅちょうこくれんぽう', 'the United Arab Emirates', 'الإمارات'],
      ['スペイン', '', 'Spain', 'إسبانيا'],
      ['メキシコ', '', 'Mexico', 'المكسيك'],
      ['ドイツ', '', 'Germany', 'ألمانيا'],
      ['オランダ', '', 'the Netherlands', 'هولندا'],
      ['ロシア', '', 'Russia', 'روسيا'],
      ['フランス', '', 'France', 'فرنسا'],
      ['イタリア', '', 'Italy', 'إيطاليا'],
      ['ブラジル', '', 'Brazil', 'البرازيل'],
      ['インド', '', 'India', 'الهند'],
      ['中国', 'ちゅうごく', 'China', 'الصين'],
      ['韓国', 'かんこく', 'South Korea', 'كوريا الجنوبية'],
      ['トルコ', '', 'Turkey', 'تركيا'],
    ] as Array<[string, string, string, string]>
  ).map(([s, r, en, ar]) => w(s, r, en, ar)),
];

export const LEXICON = new Lexicon(LEXICON_ENTRIES);

// ---------------- slots ----------------

const opt = (id: string, ja: string, ja_keys: string[], en: string[], ar: string[]): SlotOption => {
  const e = LEXICON.get(ja);
  if (!e) throw new Error(`Slot option ${id}: ${ja} is not in the lexicon`);
  return { id, ja, gloss: { en: e.en.replace(/ \(.*\)$/, ''), ar: e.ar.replace(/ \(.*\)$/, '') }, keys: { ja: [ja, ...ja_keys], en, ar } };
};

const ITEMS: SlotOption[] = [
  opt('coffee', 'コーヒー', ['kohi', 'koohii', 'koh-hi'], ['coffee'], ['قهوة', 'القهوة', 'كوب قهوة', 'قهوه']),
  opt('blackTea', '紅茶', ['こうちゃ', 'koucha', 'kocha'], ['black tea', 'tea'], ['شاي', 'شاي أسود', 'الشاي']),
  opt('greenTea', 'お茶', ['おちゃ', 'ocha'], ['green tea', 'japanese tea'], ['شاي أخضر', 'الشاي الأخضر']),
  opt('latte', 'カフェラテ', ['ラテ', 'かふぇらて', 'latte'], ['latte', 'cafe latte', 'café latte'], ['لاتيه', 'كافيه لاتيه', 'لاتي']),
  opt('juice', 'ジュース', ['jusu'], ['juice', 'orange juice'], ['عصير', 'العصير']),
  opt('water', '水', ['みず', 'mizu'], ['water'], ['ماء', 'الماء', 'مياه', 'ميه', 'مويه']),
  opt('milk', '牛乳', ['ぎゅうにゅう', 'ミルク', 'gyunyu', 'gyuunyuu'], ['milk'], ['حليب', 'الحليب', 'لبن']),
  opt('onigiri', 'おにぎり', ['onigiri'], ['onigiri', 'rice ball', 'rice balls'], ['أونيغيري', 'اونيغيري', 'أونيجيري', 'كرة أرز', 'كرات أرز']),
  opt('sandwich', 'サンドイッチ', ['sandoicchi'], ['sandwich'], ['ساندويتش', 'ساندوتش', 'سندويتش', 'سندوتش']),
  opt('bento', 'お弁当', ['べんとう', 'bento'], ['bento', 'lunch box', 'lunchbox', 'boxed lunch'], ['بنتو', 'بينتو', 'وجبة غداء']),
  opt('cake', 'ケーキ', ['keki'], ['cake'], ['كعكة', 'كيك', 'كيكة', 'الكيك']),
];

const PLACES: SlotOption[] = [
  opt('toilet', 'トイレ', ['といれ', 'toire', 'おてあらい'], ['toilet', 'restroom', 'bathroom', 'washroom'], ['الحمام', 'حمام', 'دورة المياه', 'المرحاض', 'تواليت']),
  opt('station', '駅', ['えき', 'eki'], ['station', 'train station'], ['المحطة', 'محطة', 'محطة القطار']),
  opt('shibuya', '渋谷', ['しぶや', 'shibuya'], ['shibuya'], ['شيبويا']),
  opt('shinjuku', '新宿', ['しんじゅく', 'shinjuku'], ['shinjuku'], ['شينجوكو', 'شنجوكو']),
  opt('asakusa', '浅草', ['あさくさ', 'asakusa'], ['asakusa'], ['أساكوسا', 'اساكوسا']),
  opt('akihabara', '秋葉原', ['あきはばら', 'akihabara'], ['akihabara'], ['أكيهابارا', 'اكيهابارا']),
  opt('ueno', '上野', ['うえの', 'ueno'], ['ueno'], ['أوينو', 'اوينو']),
  opt('tokyoStation', '東京駅', ['とうきょうえき', 'とうきょう', '東京', 'tokyo'], ['tokyo station', 'tokyo'], ['محطة طوكيو', 'طوكيو']),
  opt('airport', '空港', ['くうこう', 'kuukou', 'kuko'], ['airport'], ['المطار', 'مطار']),
];

const COUNTRIES: SlotOption[] = [
  ['アメリカ', ['america', 'amerika'], ['usa', 'united states', 'america', 'the us', 'us'], ['أمريكا', 'امريكا', 'الولايات المتحدة']],
  ['イギリス', ['igirisu'], ['uk', 'united kingdom', 'england', 'britain', 'great britain'], ['بريطانيا', 'انجلترا', 'إنجلترا', 'المملكة المتحدة']],
  ['カナダ', ['kanada'], ['canada'], ['كندا']],
  ['オーストラリア', ['osutorarua'], ['australia'], ['أستراليا', 'استراليا']],
  ['エジプト', ['ejiputo'], ['egypt'], ['مصر']],
  ['サウジアラビア', ['saujiarabia'], ['saudi arabia', 'saudi'], ['السعودية', 'المملكة العربية السعودية']],
  ['ヨルダン', ['yorudan'], ['jordan'], ['الأردن', 'الاردن']],
  ['レバノン', ['rebanon'], ['lebanon'], ['لبنان']],
  ['シリア', ['shiria'], ['syria'], ['سوريا', 'سورية']],
  ['パレスチナ', ['paresuchina'], ['palestine'], ['فلسطين']],
  ['イラク', ['iraku'], ['iraq'], ['العراق']],
  ['モロッコ', ['morokko'], ['morocco'], ['المغرب']],
  ['アルジェリア', ['arujeria'], ['algeria'], ['الجزائر']],
  ['チュニジア', ['chunijia'], ['tunisia'], ['تونس']],
  ['リビア', ['ribia'], ['libya'], ['ليبيا']],
  ['スーダン', ['sudan'], ['sudan'], ['السودان']],
  ['イエメン', ['iemen'], ['yemen'], ['اليمن']],
  ['クウェート', ['kuweto'], ['kuwait'], ['الكويت']],
  ['カタール', ['kataru'], ['qatar'], ['قطر']],
  ['オマーン', ['oman'], ['oman'], ['عمان', 'عُمان']],
  ['バーレーン', ['bareen'], ['bahrain'], ['البحرين']],
  ['アラブ首長国連邦', ['uae', 'arabushuchokokurenpo'], ['uae', 'united arab emirates', 'emirates', 'dubai', 'abu dhabi'], ['الإمارات', 'الامارات', 'دبي', 'أبو ظبي']],
  ['スペイン', ['supein'], ['spain'], ['إسبانيا', 'اسبانيا']],
  ['メキシコ', ['mekishiko'], ['mexico'], ['المكسيك']],
  ['ドイツ', ['doitsu'], ['germany'], ['ألمانيا', 'المانيا']],
  ['オランダ', ['oranda'], ['netherlands', 'the netherlands', 'holland'], ['هولندا']],
  ['ロシア', ['roshia'], ['russia'], ['روسيا']],
  ['フランス', ['furansu'], ['france'], ['فرنسا']],
  ['イタリア', ['itaria'], ['italy'], ['إيطاليا', 'ايطاليا']],
  ['ブラジル', ['burajiru'], ['brazil'], ['البرازيل']],
  ['インド', ['indo'], ['india'], ['الهند']],
  ['中国', ['ちゅうごく', 'chugoku'], ['china'], ['الصين']],
  ['韓国', ['かんこく', 'kankoku'], ['south korea', 'korea'], ['كوريا', 'كوريا الجنوبية']],
  ['トルコ', ['toruko'], ['turkey', 'turkiye'], ['تركيا']],
].map(([ja, jk, en, ar]) => opt(`c_${ja}`, ja as string, jk as string[], en as string[], ar as string[]));

const HOBBIES: SlotOption[] = [
  opt('anime', 'アニメ', ['anime'], ['anime'], ['أنمي', 'الأنمي', 'انمي', 'الانمي']),
  opt('manga', '漫画', ['まんが', 'マンガ', 'manga'], ['manga', 'comics'], ['مانغا', 'مانجا', 'المانغا']),
  opt('music', '音楽', ['おんがく', 'ongaku'], ['music', 'listening to music'], ['موسيقى', 'الموسيقى', 'موسيقا']),
  opt('photo', '写真', ['しゃしん', 'shashin'], ['photography', 'photos', 'taking photos', 'photo', 'taking pictures'], ['التصوير', 'تصوير', 'الصور']),
  opt('games', 'ゲーム', ['geimu'], ['games', 'video games', 'gaming', 'game'], ['ألعاب', 'الألعاب', 'العاب', 'ألعاب الفيديو']),
  opt('sports', 'スポーツ', ['supotsu'], ['sports', 'sport'], ['الرياضة', 'رياضة']),
  opt('cooking', '料理', ['りょうり', 'ryori', 'ryouri'], ['cooking', 'food'], ['الطبخ', 'طبخ']),
  opt('movies', '映画', ['えいが', 'eiga'], ['movies', 'films', 'cinema', 'movie'], ['الأفلام', 'أفلام', 'افلام', 'السينما']),
  opt('travel', '旅行', ['りょこう', 'ryoko', 'ryokou'], ['travel', 'traveling', 'travelling'], ['السفر', 'سفر']),
  opt('books', '本', ['ほん', 'どくしょ', 'hon'], ['books', 'reading', 'book'], ['الكتب', 'كتب', 'القراءة']),
  opt('drawing', '絵', ['え', 'e'], ['drawing', 'painting', 'art'], ['الرسم', 'رسم']),
];

const FLAVORS: SlotOption[] = [
  opt('shoyu', 'しょうゆ', ['醤油', 'shoyu', 'shouyu'], ['soy sauce', 'shoyu', 'soy'], ['صويا', 'صلصة الصويا']),
  opt('miso', 'みそ', ['味噌', 'miso'], ['miso'], ['ميسو', 'ميزو']),
  opt('tonkotsu', 'とんこつ', ['豚骨', 'tonkotsu'], ['tonkotsu', 'pork bone'], ['تونكوتسو']),
];

export const SLOTS: Record<string, SlotOption[]> = {
  item: ITEMS,
  place: PLACES,
  thing: [...ITEMS, ...PLACES],
  country: COUNTRIES,
  hobby: HOBBIES,
  flavor: FLAVORS,
};

export function slotOption(slot: string, id: string): SlotOption | undefined {
  return SLOTS[slot]?.find((o) => o.id === id);
}
