import type { Character } from '../types';

export const CHARACTERS: Character[] = [
  {
    id: 'yuki',
    name: { ja: 'ゆき', reading: 'ゆき', en: 'Yuki', ar: 'يوكي' },
    age: 24,
    job: { en: 'Barista at Sakura Café', ar: 'باريستا في مقهى ساكورا' },
    bio: {
      en: 'Cheerful and chatty. Plays guitar on weekends and knows every song on the café playlist.',
      ar: 'مرحة وكثيرة الكلام. تعزف الغيتار في عطلات نهاية الأسبوع وتعرف كل أغنية في قائمة المقهى.',
    },
    personality: { en: 'Cheerful, patient', ar: 'مرحة وصبورة' },
    interests: ['music', 'art', 'food'],
    speaking: { rate: 1.0, pitch: 1.25, voice: 'f' },
    avatar: {
      skin: '#f6d3ba',
      hair: { style: 'bob', color: '#5b3a2e' },
      top: '#f7f2ea',
      bottom: '#38405f',
      shoes: '#ffffff',
      accent: '#ee8fa6',
      accessories: ['apron'],
    },
    locationId: 'cafe',
    scenarioId: 'cafe',
  },
  {
    id: 'tanaka',
    name: { ja: '田中', reading: 'たなか', en: 'Tanaka', ar: 'تاناكا' },
    age: 31,
    job: { en: 'Convenience store clerk', ar: 'موظف في متجر كونبيني' },
    bio: {
      en: 'Works the evening shift and plays games all night. Polite, calm and a little sleepy.',
      ar: 'يعمل في الوردية المسائية ويلعب الألعاب طوال الليل. مهذب وهادئ وناعس قليلًا.',
    },
    personality: { en: 'Polite, calm', ar: 'مهذب وهادئ' },
    interests: ['gaming', 'tech', 'anime'],
    speaking: { rate: 0.95, pitch: 0.95, voice: 'm' },
    avatar: {
      skin: '#f0c9a6',
      hair: { style: 'short', color: '#211c1e' },
      top: '#2aa198',
      bottom: '#2d3142',
      shoes: '#2b2b33',
      accent: '#ffffff',
      accessories: ['glasses'],
    },
    locationId: 'konbini',
    scenarioId: 'konbini',
  },
  {
    id: 'sato',
    name: { ja: '佐藤', reading: 'さとう', en: 'Sato', ar: 'ساتو' },
    age: 58,
    job: { en: 'Station attendant', ar: 'موظف محطة' },
    bio: {
      en: 'Has worked at the station for thirty years. Speaks slowly and clearly, and loves trains and local history.',
      ar: 'يعمل في المحطة منذ ثلاثين عامًا. يتحدث ببطء ووضوح، ويحب القطارات وتاريخ المنطقة.',
    },
    personality: { en: 'Kind, formal, slow-spoken', ar: 'لطيف ورسمي وبطيء الكلام' },
    interests: ['history', 'travel', 'culture'],
    speaking: { rate: 0.8, pitch: 0.8, voice: 'm' },
    avatar: {
      skin: '#e9c19c',
      hair: { style: 'short', color: '#9a9aa2' },
      top: '#2f3f6e',
      bottom: '#2f3f6e',
      shoes: '#1d1d24',
      accent: '#d9b44a',
      accessories: ['cap', 'tie'],
    },
    locationId: 'station',
    scenarioId: 'station',
  },
  {
    id: 'kenji',
    name: { ja: 'けんじ', reading: 'けんじ', en: 'Kenji', ar: 'كينجي' },
    age: 45,
    job: { en: 'Ramen chef and shop owner', ar: 'طاهي رامن وصاحب المحل' },
    bio: {
      en: 'Loud, warm and proud of his broth. Talks about baseball and food with everyone who sits at his counter.',
      ar: 'صوته عالٍ ودافئ ويفخر بمرقه. يتحدث عن البيسبول والطعام مع كل من يجلس عند طاولته.',
    },
    personality: { en: 'Jolly, loud, generous', ar: 'مرح وصوته عالٍ وكريم' },
    interests: ['food', 'sports', 'culture'],
    speaking: { rate: 1.1, pitch: 0.7, voice: 'm' },
    avatar: {
      skin: '#efc39a',
      hair: { style: 'short', color: '#2a2220' },
      top: '#f7f4ee',
      bottom: '#27346b',
      shoes: '#1f1f26',
      accent: '#d8433f',
      accessories: ['headband', 'apron'],
      stocky: 1.18,
      height: 0.97,
    },
    locationId: 'ramen',
    scenarioId: 'ramen',
  },
  {
    id: 'mio',
    name: { ja: 'ミオ', reading: 'みお', en: 'Mio', ar: 'ميو' },
    age: 19,
    job: { en: 'University student', ar: 'طالبة جامعية' },
    bio: {
      en: 'Photographs the cherry trees every spring and watches anime between classes. Curious about everyone she meets.',
      ar: 'تصوّر أشجار الكرز كل ربيع وتشاهد الأنمي بين المحاضرات. فضولية تجاه كل من تقابله.',
    },
    personality: { en: 'Curious, friendly', ar: 'فضولية وودودة' },
    interests: ['anime', 'photo', 'music'],
    speaking: { rate: 1.1, pitch: 1.35, voice: 'f' },
    avatar: {
      skin: '#f8dcc6',
      hair: { style: 'ponytail', color: '#3a2c3e' },
      top: '#9d8be0',
      bottom: '#ebe5da',
      shoes: '#f06292',
      accent: '#f4c542',
      accessories: ['camera', 'backpack'],
    },
    locationId: 'park',
    scenarioId: 'park',
  },
  {
    id: 'hanako',
    name: { ja: '花子先生', reading: 'はなこせんせい', en: 'Hanako-sensei', ar: 'المعلّمة هاناكو' },
    age: 38,
    job: { en: 'Japanese teacher at the language school', ar: 'معلّمة يابانية في مدرسة اللغات' },
    bio: {
      en: 'Teaches beginners with games and songs. Never rushes you and always has a sticker for a good answer.',
      ar: 'تعلّم المبتدئين بالألعاب والأغاني. لا تستعجلك أبدًا ولديها دائمًا ملصق للإجابة الجيدة.',
    },
    personality: { en: 'Warm, encouraging', ar: 'دافئة ومشجّعة' },
    interests: ['books', 'culture', 'travel'],
    speaking: { rate: 0.85, pitch: 1.1, voice: 'f' },
    avatar: {
      skin: '#f4d0b4',
      hair: { style: 'bun', color: '#2b2023' },
      top: '#7fa8a2',
      bottom: '#4a4a55',
      shoes: '#5a4a44',
      accent: '#e7e2d6',
      accessories: ['glasses', 'scarf'],
    },
    locationId: 'school',
    lessonId: 'greetings',
  },
];

export const characterById = (id: string) => CHARACTERS.find((c) => c.id === id);
