import type { Character } from '../types';

/** Additional characters (new friends, job-site staff) — docs/GAME_DESIGN.md §8.2. Each `scenarioId` is the character's default
 * scenario; scenarios that do not exist yet are authored by later slices (the world skips a spawn whose scenario is missing). */
export const EXTRA_CHARACTERS: Character[] = [
  {
    id: 'aiko',
    name: { ja: '小野 愛子', reading: 'おの あいこ', en: 'Aiko Ono', ar: 'أيكو أونو' },
    age: 68,
    job: { en: 'Tea-house owner and landlady', ar: 'صاحبة بيت شاي ومؤجّرة' },
    bio: {
      en: 'Runs the tea and sweets stall under her old apartment building. Slow, warm, and always has a snack for you.',
      ar: 'تدير كشك الشاي والحلوى أسفل مبنى شققها القديم. هادئة ودافئة ولديها دائمًا وجبة خفيفة لك.',
    },
    personality: { en: 'Gentle, patient', ar: 'لطيفة وصبورة' },
    interests: ['culture', 'nature', 'family', 'food'],
    speaking: { rate: 0.8, pitch: 1.0, voice: 'f' },
    avatar: {
      skin: '#efc7a8',
      hair: { style: 'bun', color: '#b9b9c4' },
      top: '#8a6f8e',
      bottom: '#4a4a55',
      shoes: '#5a4a44',
      accent: '#e7e2d6',
      accessories: ['apron', 'glasses'],
      height: 0.94,
    },
    locationId: 'ono',
    scenarioId: 'aiko_tea',
  },
  {
    id: 'rin',
    name: { ja: '高橋 凜', reading: 'たかはし りん', en: 'Rin Takahashi', ar: 'رين تاكاهاشي' },
    age: 16,
    job: { en: "Student, works at her aunt's shop", ar: 'طالبة، تعمل في متجر عمّتها' },
    bio: {
      en: 'Sharp, funny, talks fast. Knows every second-hand bargain and every meme.',
      ar: 'ذكية ومرحة وتتحدث بسرعة. تعرف كل صفقة مستعملة وكل ميم.',
    },
    personality: { en: 'Quick, cheeky', ar: 'سريعة البديهة ومشاكسة' },
    interests: ['fashion', 'gaming', 'social'],
    speaking: { rate: 1.15, pitch: 1.3, voice: 'f' },
    avatar: {
      skin: '#f4d0b4',
      hair: { style: 'short', color: '#7a2f3a' },
      top: '#ee8fa6',
      bottom: '#2d3142',
      shoes: '#ffffff',
      accent: '#f4c542',
      accessories: ['beanie'],
    },
    locationId: 'fukufuku',
    scenarioId: 'fuku_clothes',
  },
  {
    id: 'nakamura',
    name: { ja: '中村 大地', reading: 'なかむら だいち', en: 'Daichi Nakamura', ar: 'داييتشي ناكامورا' },
    age: 36,
    job: { en: 'Mechanic and owner of Nakamura Motors', ar: 'ميكانيكي وصاحب ورشة ناكامورا' },
    bio: {
      en: "Grew up in his father's garage. Gruff voice, soft heart; treats customers like neighbours.",
      ar: 'نشأ في ورشة أبيه. صوته خشن وقلبه رقيق ويعامل الزبائن كجيران.',
    },
    personality: { en: 'Gruff, kind', ar: 'خشن وطيب' },
    interests: ['cars', 'sports', 'family'],
    speaking: { rate: 1.0, pitch: 0.75, voice: 'm' },
    avatar: {
      skin: '#e9c19c',
      hair: { style: 'short', color: '#2a2220' },
      top: '#2f5ea8',
      bottom: '#2f5ea8',
      shoes: '#1d1d24',
      accent: '#f4c542',
      accessories: ['cap'],
      stocky: 1.1,
    },
    locationId: 'motors',
    scenarioId: 'motors_visit',
  },
  {
    id: 'aoi',
    name: { ja: '鈴木 葵', reading: 'すずき あおい', en: 'Aoi Suzuki', ar: 'أوي سوزوكي' },
    age: 24,
    job: { en: 'Clerk at Hikari Denki', ar: 'موظفة في متجر هيكاري دنكي' },
    bio: {
      en: 'Loves gadgets and games. Speaks careful shop Japanese and explains prices very clearly.',
      ar: 'تحب الأجهزة والألعاب. تتحدث يابانية المتاجر بعناية وتشرح الأسعار بوضوح شديد.',
    },
    personality: { en: 'Careful, polite', ar: 'دقيقة ومهذبة' },
    interests: ['tech', 'gaming', 'social'],
    speaking: { rate: 1.0, pitch: 1.2, voice: 'f' },
    avatar: {
      skin: '#f3cdb0',
      hair: { style: 'ponytail', color: '#2f2a44' },
      top: '#1f5fbf',
      bottom: '#2d3142',
      shoes: '#ffffff',
      accent: '#ffd166',
      accessories: ['glasses'],
    },
    locationId: 'denki',
    scenarioId: 'denki_phone',
  },
  {
    id: 'kato',
    name: { ja: '加藤', reading: 'かとう', en: 'Kato', ar: 'كاتو' },
    age: 52,
    job: { en: 'Souvenir shop owner, Hikarigaoka', ar: 'صاحب متجر هدايا تذكارية في هيكاريغاؤكا' },
    bio: {
      en: 'Sells sweets and keychains by the station and loves telling visitors about the neighbourhood.',
      ar: 'يبيع الحلوى وميداليات المفاتيح بجوار المحطة ويحب إخبار الزوار عن الحيّ.',
    },
    personality: { en: 'Chatty, welcoming', ar: 'ثرثار ومضياف' },
    interests: ['travel', 'food', 'history'],
    speaking: { rate: 1.0, pitch: 0.9, voice: 'm' },
    avatar: {
      skin: '#e9c19c',
      hair: { style: 'short', color: '#4a4a55' },
      top: '#7aa0c4',
      bottom: '#3a3f50',
      shoes: '#4a3f3a',
      accent: '#f4f4f4',
      accessories: ['apron'],
    },
    locationId: 'hikarigaoka',
    scenarioId: 'trip_hikarigaoka',
  },
  {
    id: 'hina',
    name: { ja: 'ひな', reading: 'ひな', en: 'Hina', ar: 'هينا' },
    age: 7, // only in home_kenji, simple A1 lines
    job: { en: "Kenji's daughter", ar: 'ابنة كينجي' },
    bio: { en: 'Seven years old and very curious.', ar: 'عمرها سبع سنوات وفضولية جدًا.' },
    personality: { en: 'Curious', ar: 'فضولية' },
    interests: ['art', 'nature'],
    speaking: { rate: 1.1, pitch: 1.5, voice: 'f' },
    avatar: {
      skin: '#f8dcc6',
      hair: { style: 'ponytail', color: '#3a2b2a' },
      top: '#f4c542',
      bottom: '#4f86f7',
      shoes: '#ffffff',
      accent: '#ee8fa6',
      accessories: [],
      height: 0.62,
    },
    locationId: 'home_kenji',
  },
];
