// UI strings for microphone, speaker and diagnostics. Every key needs an English and an Arabic string; keys are prefixed 'audio.'.

export const en = {
  'audio.title': 'Microphone & speaker check',
  'audio.sub': 'Find out why you cannot hear Japanese or talk to the characters, and how to fix it.',
  'audio.checking': 'Checking…',
  'audio.recheck': 'Re-check',

  // status rows
  'audio.row.speaker': 'Speaker',
  'audio.row.voices': 'Japanese voices',
  'audio.row.mic': 'Microphone permission',
  'audio.row.stt': 'Speech recognition',
  'audio.row.secure': 'Secure connection',
  'audio.row.embedded': 'Opened directly',

  'audio.speaker.ready': 'Ready',
  'audio.speaker.noVoice': 'No Japanese voice installed',
  'audio.speaker.none': 'Not supported in this browser',
  'audio.voices.none': 'None found',
  'audio.voices.more': '+{n} more',
  'audio.mic.granted': 'Allowed',
  'audio.mic.denied': 'Blocked',
  'audio.mic.prompt': 'Needs permission',
  'audio.mic.unknown': 'Not known until you allow it',
  'audio.mic.none': 'No microphone found',
  'audio.stt.yes': 'Supported',
  'audio.stt.no': 'Not supported in this browser',
  'audio.secure.yes': 'Yes (https)',
  'audio.secure.no': 'No, the microphone is blocked',
  'audio.embedded.no': 'Yes',
  'audio.embedded.yes': 'No, inside another page',

  // what to do about each issue
  'audio.fix.heading': 'What to do',
  'audio.fix.allGood': 'Everything looks fine. Use the tests below to hear and speak once.',
  'audio.fix.insecure': 'This page is not on a secure (https) address, so the browser blocks the microphone. Open the https address of the app instead.',
  'audio.fix.embedded': 'This page is running inside another page, which blocks the microphone. Open it directly in its own tab in Chrome or Safari.',
  'audio.fix.noTts': 'This browser cannot speak aloud. Open the app in Chrome, Edge or Safari.',
  'audio.fix.noJa': 'No Japanese voice is installed on this device, so lines are shown but not spoken. Install one, then come back and tap Re-check.',
  'audio.fix.noJa.android': 'Android: Settings > System > Languages > Text-to-speech output > Google Speech Services > Install voice data > Japanese.',
  'audio.fix.noJa.ios': 'iPhone and iPad: Settings > Accessibility > Spoken Content > Voices > Japanese, then download a voice.',
  'audio.fix.noJa.windows': 'Windows: Settings > Time & language > Language & region > Add Japanese, then install its Speech option.',
  'audio.fix.noJa.mac': 'Mac: System Settings > Accessibility > Spoken Content > System voice > Manage Voices > Japanese.',
  'audio.fix.noJa.other': 'Install a Japanese text-to-speech voice in your device settings (look for Text-to-speech or Spoken Content).',
  'audio.fix.noStt': 'This browser cannot turn your voice into text. Typing and suggestions still work. For voice, open this page directly in Chrome, Edge or Safari.',
  'audio.fix.noStt.firefox': 'Firefox cannot turn your voice into text. Typing still works. For voice, open this page directly in Chrome or Safari.',
  'audio.fix.micDenied': 'Microphone access is blocked. Tap the lock, tune or aA icon next to the address, set Microphone to Allow, reload, then tap Re-check.',
  'audio.fix.micPrompt': 'The browser has not asked for the microphone yet. Tap Allow microphone and choose Allow.',
  'audio.fix.noMic': 'No microphone was found. Plug one in or turn it on, then tap Re-check.',
  'audio.fix.iosGesture': 'On iPhone and iPad sound only starts after a tap. Tap Test speaker, and check the silent switch and volume.',

  // buttons
  'audio.btn.testSpeaker': 'Test speaker',
  'audio.btn.allowMic': 'Allow microphone',
  'audio.btn.testMic': 'Test microphone',
  'audio.btn.stopMic': 'Stop',
  'audio.btn.retryMic': 'Try again',
  'audio.btn.speaking': 'Speaking…',
  'audio.btn.working': 'Please wait…',

  // test results
  'audio.spk.hint': 'You should hear a Japanese greeting.',
  'audio.spk.playing': 'Playing…',
  'audio.spk.ok': 'Played with the voice “{voice}”. If you heard nothing, raise the volume and check the silent switch.',
  'audio.spk.okNoName': 'Played with the default voice. If you heard nothing, raise the volume and check the silent switch.',
  'audio.spk.silent': 'Nothing could be played. Raise the volume, check the silent switch, then try again.',
  'audio.spk.err.unavailable': 'This browser cannot speak aloud. Open the app in Chrome, Edge or Safari.',
  'audio.spk.err.no-voice': 'No Japanese voice is installed on this device. See the steps above to install one.',
  'audio.spk.err.not-allowed': 'The browser blocked the sound. Tap the button again, and open the app directly in its own tab if it is embedded.',
  'audio.spk.err.synthesis-failed': 'The voice failed to play. Try again, or pick a different voice in your device settings.',
  'audio.spk.err.timeout': 'The voice did not start in time. Try again.',
  'audio.mic.allowedOk': 'Microphone allowed.',
  'audio.mic.fail.denied': 'Microphone access was refused. Allow it in the browser settings for this site, then tap Re-check.',
  'audio.mic.fail.no-device': 'No microphone was found. Plug one in or turn it on, then tap Re-check.',
  'audio.mic.fail.insecure': 'The microphone only works on a secure (https) address.',
  'audio.mic.fail.blocked': 'This page is embedded and cannot use the microphone. Open it directly in its own tab in Chrome or Safari.',
  'audio.mic.fail.unknown': 'The microphone could not be started. Try again, or reload the page.',
  'audio.mic.sayPrompt': 'Tap, then say something in Japanese, for example こんにちは.',
  'audio.mic.listening': 'Listening… speak now.',
  'audio.mic.heard': 'Heard',
  'audio.mic.confidence': 'Confidence {n}%',
  'audio.mic.noConfidence': 'Confidence not reported',

  // recognition errors, also used on the conversation screen
  'audio.mic.err.unsupported': 'Voice input is not supported in this browser. Type instead, or open the app in Chrome, Edge or Safari.',
  'audio.mic.err.denied': 'Microphone access is blocked. Allow it for this site, or type instead.',
  'audio.mic.err.blocked': 'Speech recognition is blocked here. Open the app directly in Chrome or Safari, or type instead.',
  'audio.mic.err.silent': 'I did not hear anything. Move closer and try again.',
  'audio.mic.err.no-mic': 'No microphone was found. Plug one in, or type instead.',
  'audio.mic.err.network': 'Speech recognition needs an internet connection. Check it and try again.',
  'audio.mic.err.cancelled': 'Listening was cancelled. Tap to try again.',
  'audio.mic.err.language': 'This browser cannot recognise Japanese speech. Type instead.',
  'audio.mic.err.timeout': 'Listening timed out. Tap and speak right away.',
  'audio.mic.err.unknown': 'Voice input did not work. Try again, or type instead.',
  'audio.mic.checkBtn': 'Check audio',

  // consent, adult gate and the listening waiver (docs/GAME_DESIGN.md §7.6)
  'audio.consent': 'On Chrome, voice recognition sends your audio to Google. Typing never leaves your device. Allow voice input?',
  'audio.consentKids': 'Voice input is off. A grown-up can turn it on in Settings.',
  'audio.parentGate': 'Grown-ups only: what is {a} + {b}?',
  'audio.listenOff': "I can't listen: show text, no penalty",
} as const;

export const ar: Record<keyof typeof en, string> = {
  'audio.title': 'فحص الميكروفون والسماعة',
  'audio.sub': 'اعرف سبب عدم سماع اليابانية أو عدم القدرة على التحدث مع الشخصيات، وكيف تصلحه.',
  'audio.checking': 'جارٍ الفحص…',
  'audio.recheck': 'إعادة الفحص',

  'audio.row.speaker': 'السماعة',
  'audio.row.voices': 'الأصوات اليابانية',
  'audio.row.mic': 'إذن الميكروفون',
  'audio.row.stt': 'التعرّف على الكلام',
  'audio.row.secure': 'اتصال آمن',
  'audio.row.embedded': 'فُتحت مباشرة',

  'audio.speaker.ready': 'جاهزة',
  'audio.speaker.noVoice': 'لا يوجد صوت ياباني مثبّت',
  'audio.speaker.none': 'غير مدعومة في هذا المتصفح',
  'audio.voices.none': 'لا يوجد',
  'audio.voices.more': '+{n} أخرى',
  'audio.mic.granted': 'مسموح',
  'audio.mic.denied': 'محظور',
  'audio.mic.prompt': 'يحتاج إلى إذن',
  'audio.mic.unknown': 'غير معروف حتى تسمح به',
  'audio.mic.none': 'لم يُعثر على ميكروفون',
  'audio.stt.yes': 'مدعوم',
  'audio.stt.no': 'غير مدعوم في هذا المتصفح',
  'audio.secure.yes': 'نعم (https)',
  'audio.secure.no': 'لا، الميكروفون محظور',
  'audio.embedded.no': 'نعم',
  'audio.embedded.yes': 'لا، داخل صفحة أخرى',

  'audio.fix.heading': 'ما العمل',
  'audio.fix.allGood': 'كل شيء يبدو سليمًا. استخدم الاختبارات أدناه لتسمع وتتحدث مرة واحدة.',
  'audio.fix.insecure': 'هذه الصفحة ليست على عنوان آمن (https) لذلك يحظر المتصفح الميكروفون. افتح عنوان https الخاص بالتطبيق.',
  'audio.fix.embedded': 'هذه الصفحة تعمل داخل صفحة أخرى وهذا يحظر الميكروفون. افتحها مباشرة في تبويب مستقل في Chrome أو Safari.',
  'audio.fix.noTts': 'هذا المتصفح لا يستطيع القراءة بصوت مسموع. افتح التطبيق في Chrome أو Edge أو Safari.',
  'audio.fix.noJa': 'لا يوجد صوت ياباني مثبّت على هذا الجهاز، لذلك تظهر الجمل دون نطق. ثبّت واحدًا ثم عُد واضغط إعادة الفحص.',
  'audio.fix.noJa.android': 'أندرويد: الإعدادات > النظام > اللغات > مخرجات تحويل النص إلى كلام > خدمات Google للكلام > تثبيت بيانات الصوت > اليابانية.',
  'audio.fix.noJa.ios': 'آيفون وآيباد: الإعدادات > تسهيلات الاستخدام > المحتوى المنطوق > الأصوات > اليابانية، ثم نزّل صوتًا.',
  'audio.fix.noJa.windows': 'ويندوز: الإعدادات > الوقت واللغة > اللغة والمنطقة > أضف اليابانية، ثم ثبّت خيار الكلام الخاص بها.',
  'audio.fix.noJa.mac': 'ماك: إعدادات النظام > تسهيلات الاستخدام > المحتوى المنطوق > صوت النظام > إدارة الأصوات > اليابانية.',
  'audio.fix.noJa.other': 'ثبّت صوتًا يابانيًا لتحويل النص إلى كلام من إعدادات جهازك (ابحث عن تحويل النص إلى كلام أو المحتوى المنطوق).',
  'audio.fix.noStt': 'هذا المتصفح لا يحوّل صوتك إلى نص. الكتابة والاقتراحات تعمل. للتحدث بالصوت افتح هذه الصفحة مباشرة في Chrome أو Edge أو Safari.',
  'audio.fix.noStt.firefox': 'متصفح Firefox لا يحوّل صوتك إلى نص. الكتابة تعمل. للتحدث بالصوت افتح هذه الصفحة مباشرة في Chrome أو Safari.',
  'audio.fix.micDenied': 'الوصول إلى الميكروفون محظور. المس أيقونة القفل أو الإعدادات أو aA بجوار العنوان، واجعل الميكروفون «السماح»، ثم أعد التحميل واضغط إعادة الفحص.',
  'audio.fix.micPrompt': 'لم يطلب المتصفح إذن الميكروفون بعد. اضغط «السماح بالميكروفون» ثم اختر السماح.',
  'audio.fix.noMic': 'لم يُعثر على ميكروفون. وصّل واحدًا أو شغّله ثم اضغط إعادة الفحص.',
  'audio.fix.iosGesture': 'على آيفون وآيباد لا يبدأ الصوت إلا بعد لمسة. اضغط «اختبار السماعة» وتحقق من مفتاح الصامت ومستوى الصوت.',

  'audio.btn.testSpeaker': 'اختبار السماعة',
  'audio.btn.allowMic': 'السماح بالميكروفون',
  'audio.btn.testMic': 'اختبار الميكروفون',
  'audio.btn.stopMic': 'إيقاف',
  'audio.btn.retryMic': 'حاول مجددًا',
  'audio.btn.speaking': 'جارٍ النطق…',
  'audio.btn.working': 'يرجى الانتظار…',

  'audio.spk.hint': 'يجب أن تسمع تحية باليابانية.',
  'audio.spk.playing': 'جارٍ التشغيل…',
  'audio.spk.ok': 'تم التشغيل بصوت «{voice}». إن لم تسمع شيئًا فارفع مستوى الصوت وتحقق من مفتاح الصامت.',
  'audio.spk.okNoName': 'تم التشغيل بالصوت الافتراضي. إن لم تسمع شيئًا فارفع مستوى الصوت وتحقق من مفتاح الصامت.',
  'audio.spk.silent': 'تعذّر تشغيل أي صوت. ارفع مستوى الصوت وتحقق من مفتاح الصامت ثم حاول مجددًا.',
  'audio.spk.err.unavailable': 'هذا المتصفح لا يستطيع القراءة بصوت مسموع. افتح التطبيق في Chrome أو Edge أو Safari.',
  'audio.spk.err.no-voice': 'لا يوجد صوت ياباني مثبّت على هذا الجهاز. راجع الخطوات أعلاه لتثبيت واحد.',
  'audio.spk.err.not-allowed': 'حظر المتصفح الصوت. اضغط الزر مرة أخرى، وافتح التطبيق مباشرة في تبويب مستقل إن كان مضمّنًا.',
  'audio.spk.err.synthesis-failed': 'فشل تشغيل الصوت. حاول مجددًا أو اختر صوتًا آخر من إعدادات جهازك.',
  'audio.spk.err.timeout': 'لم يبدأ الصوت في الوقت المناسب. حاول مجددًا.',
  'audio.mic.allowedOk': 'تم السماح بالميكروفون.',
  'audio.mic.fail.denied': 'تم رفض الوصول إلى الميكروفون. اسمح به من إعدادات المتصفح لهذا الموقع ثم اضغط إعادة الفحص.',
  'audio.mic.fail.no-device': 'لم يُعثر على ميكروفون. وصّل واحدًا أو شغّله ثم اضغط إعادة الفحص.',
  'audio.mic.fail.insecure': 'الميكروفون يعمل فقط على عنوان آمن (https).',
  'audio.mic.fail.blocked': 'هذه الصفحة مضمّنة ولا تستطيع استخدام الميكروفون. افتحها مباشرة في تبويب مستقل في Chrome أو Safari.',
  'audio.mic.fail.unknown': 'تعذّر تشغيل الميكروفون. حاول مجددًا أو أعد تحميل الصفحة.',
  'audio.mic.sayPrompt': 'اضغط ثم قل شيئًا باليابانية، مثل こんにちは.',
  'audio.mic.listening': 'أستمع… تحدّث الآن.',
  'audio.mic.heard': 'سمعتُ',
  'audio.mic.confidence': 'نسبة الثقة {n}٪',
  'audio.mic.noConfidence': 'لم تُذكر نسبة الثقة',

  'audio.mic.err.unsupported': 'الإدخال الصوتي غير مدعوم في هذا المتصفح. اكتب بدلًا من ذلك، أو افتح التطبيق في Chrome أو Edge أو Safari.',
  'audio.mic.err.denied': 'الوصول إلى الميكروفون محظور. اسمح به لهذا الموقع، أو اكتب.',
  'audio.mic.err.blocked': 'التعرّف على الكلام محظور هنا. افتح التطبيق مباشرة في Chrome أو Safari، أو اكتب.',
  'audio.mic.err.silent': 'لم أسمع شيئًا. اقترب من الميكروفون وحاول مجددًا.',
  'audio.mic.err.no-mic': 'لم يُعثر على ميكروفون. وصّل واحدًا، أو اكتب.',
  'audio.mic.err.network': 'التعرّف على الكلام يحتاج إلى اتصال بالإنترنت. تحقق منه وحاول مجددًا.',
  'audio.mic.err.cancelled': 'أُلغي الاستماع. المس للمحاولة مجددًا.',
  'audio.mic.err.language': 'هذا المتصفح لا يتعرّف على الكلام الياباني. اكتب بدلًا من ذلك.',
  'audio.mic.err.timeout': 'انتهت مهلة الاستماع. المس وتحدّث فورًا.',
  'audio.mic.err.unknown': 'لم يعمل الإدخال الصوتي. حاول مجددًا أو اكتب.',
  'audio.mic.checkBtn': 'فحص الصوت',

  'audio.consent': 'في Chrome يرسل التعرّف على الصوت تسجيلك إلى Google. الكتابة لا تغادر جهازك أبدًا. هل تسمح بالإدخال الصوتي؟',
  'audio.consentKids': 'الإدخال الصوتي متوقف. يمكن لشخص بالغ تفعيله من الإعدادات.',
  'audio.parentGate': 'للبالغين فقط: كم يساوي {a} + {b}؟',
  'audio.listenOff': 'لا أستطيع الاستماع: أظهر النص دون خصم',
};
