// UI strings for culture cards and the stamp book (docs/GAME_DESIGN.md §7.6, §10). Every key needs an English and an Arabic string; keys are
// prefixed 'culture.'. The `culture.hint.<id>` lines tell a player how to find a card without naming the answer.

export const en = {
  'culture.new': 'New culture card',
  'culture.empty': 'Little notes about Japanese customs will collect here as you meet them in town and in conversations.',
  'culture.progress': '{n} of {total} cards collected',
  'culture.said': '{n} of {total} phrases said',
  'culture.intro': 'Each card is a custom you met in town. Tap a card to read it, and say its phrase out loud.',
  'culture.locked': 'Not found yet',
  'culture.hintLabel': 'Hint',
  'culture.card': 'Culture card',
  'culture.keyPhrase': 'Key phrase',
  'culture.back': 'All cards',
  'culture.open': 'Open the stamp book',
  'culture.gotIt': 'Got it',
  'culture.xp': '+{n} XP',
  'culture.sayTitle': 'Say it yourself',
  'culture.sayHint': 'Say the phrase out loud or type it. It counts for your goal and joins your review cards.',
  'culture.sayDone': 'It counts for your goal and is now in your review cards.',
  'culture.saidTag': 'Said',
  'culture.sayTag': 'Say it',
  'culture.replay': 'Hear it again',
  'culture.more': '{n} more cards waiting',
  'culture.hint.irasshaimase': 'Step into any shop and start a conversation.',
  'culture.hint.bow': 'Have your first chat with Hanako-sensei.',
  'culture.hint.konbini': 'Finish a conversation at the konbini.',
  'culture.hint.notip': 'Pay for something at the café or the ramen shop.',
  'culture.hint.itadakimasu': 'Get your first bowl of ramen.',
  'culture.hint.vending': 'Buy a drink from a vending machine.',
  'culture.hint.name': 'Finish the introduction in the park.',
  'culture.hint.gift': 'Give a friend a gift.',
  'culture.hint.hanami': 'Visit the park once Chapter 3 is done.',
  'culture.hint.keigo': 'Get a friend to switch to casual speech.',
  'culture.hint.points': 'Shop at the konbini a few times, or work perfect shifts.',
  'culture.hint.tax': 'Pay for something at Hikari Denki.',
  'culture.hint.taxfree': 'Ask about tax-free shopping at Hikari Denki.',
  'culture.hint.ic': 'Finish the IC card talk at the station.',
  'culture.hint.trainmanner': 'Ride a train.',
  'culture.hint.ticketmachine': 'Use a ticket machine at the ramen shop or the station.',
  'culture.hint.refuse': 'Politely say you will think about it at Nakamura Motors.',
  'culture.hint.bikereg': 'Buy a bicycle.',
  'culture.hint.shaken': 'Ask for the drive-away price of a car.',
} as const;

export const ar: Record<keyof typeof en, string> = {
  'culture.new': 'بطاقة ثقافية جديدة',
  'culture.empty': 'ستتجمّع هنا ملاحظات صغيرة عن العادات اليابانية كلما صادفتها في الحيّ وفي المحادثات.',
  'culture.progress': 'جمعت {n} من {total} بطاقة',
  'culture.said': 'قلت {n} من {total} عبارة',
  'culture.intro': 'كل بطاقة عادة صادفتها في الحيّ. اضغط على بطاقة لقراءتها، وقل عبارتها بصوت عالٍ.',
  'culture.locked': 'لم تُكتشف بعد',
  'culture.hintLabel': 'تلميح',
  'culture.card': 'بطاقة ثقافية',
  'culture.keyPhrase': 'العبارة الأساسية',
  'culture.back': 'كل البطاقات',
  'culture.open': 'افتح دفتر الأختام',
  'culture.gotIt': 'فهمت',
  'culture.xp': '{n} نقاط خبرة',
  'culture.sayTitle': 'قلها بنفسك',
  'culture.sayHint': 'قل العبارة بصوت عالٍ أو اكتبها. تُحتسب لهدفك وتنضم إلى بطاقات المراجعة.',
  'culture.sayDone': 'تُحتسب لهدفك وصارت الآن في بطاقات المراجعة.',
  'culture.saidTag': 'قيلت',
  'culture.sayTag': 'قلها',
  'culture.replay': 'اسمعها مرة أخرى',
  'culture.more': '{n} بطاقات أخرى بانتظارك',
  'culture.hint.irasshaimase': 'ادخل أي متجر وابدأ محادثة.',
  'culture.hint.bow': 'تحدّث لأول مرة مع هاناكو-سينسي.',
  'culture.hint.konbini': 'أنهِ محادثة في الكونبيني.',
  'culture.hint.notip': 'ادفع ثمن شيء في المقهى أو مطعم الرامن.',
  'culture.hint.itadakimasu': 'احصل على أول وعاء رامن لك.',
  'culture.hint.vending': 'اشترِ مشروبًا من آلة البيع.',
  'culture.hint.name': 'أنهِ التعارف في الحديقة.',
  'culture.hint.gift': 'قدّم هدية لصديق.',
  'culture.hint.hanami': 'زر الحديقة بعد إنهاء الفصل 3.',
  'culture.hint.keigo': 'اجعل صديقًا يتحوّل إلى الكلام العادي.',
  'culture.hint.points': 'تسوّق من الكونبيني عدة مرات، أو أنجز ورديات ممتازة.',
  'culture.hint.tax': 'ادفع ثمن شيء في هيكاري دينكي.',
  'culture.hint.taxfree': 'اسأل عن التسوق المعفى من الضريبة في هيكاري دينكي.',
  'culture.hint.ic': 'أنهِ محادثة بطاقة IC في المحطة.',
  'culture.hint.trainmanner': 'اركب القطار.',
  'culture.hint.ticketmachine': 'استخدم آلة التذاكر في مطعم الرامن أو المحطة.',
  'culture.hint.refuse': 'قل بأدب إنك ستفكّر في الأمر في ناكامورا موتورز.',
  'culture.hint.bikereg': 'اشترِ دراجة.',
  'culture.hint.shaken': 'اسأل عن السعر النهائي لسيارة.',
};
