// UI strings for the conversation's game parts and the debrief: stars, pay lines, echo, price chip, receipt, speech confirmation.
// Every key needs an English and an Arabic string with the same {placeholders}; keys are prefixed 'debrief.'.

export const en = {
  'debrief.stars': 'Stars',
  'debrief.yenTitle': 'Your pay',
  'debrief.nudge': 'Try the next one without a chip: about +¥{n}',
  'debrief.keep': 'Keep these',
  'debrief.sayIt': 'Say it',
  'debrief.echoPaid': 'Said it yourself: +¥{n}',
  // stars: what each one needed
  'debrief.star1': 'Every goal done',
  'debrief.star2': 'Mostly your own words ({pct}%+)',
  'debrief.star3': 'Own words ({pct}%+), no hints, polite requests',
  'debrief.starsNone': 'Finish every goal to earn a star.',
  // pay lines: one plain reason per row
  'debrief.pay.lines': 'Your lines',
  'debrief.pay.steps': 'All steps done',
  'debrief.pay.stepsLess': 'Some steps not done',
  'debrief.pay.prepared': 'Prepared +{pct}%',
  'debrief.pay.real': 'Real mode +{pct}%',
  'debrief.pay.firstPhrase': 'First time you said this',
  'debrief.pay.star': 'Star {n}',
  'debrief.pay.repeat': 'Played already today',
  'debrief.pay.softCap': 'Shops are quiet today',
  'debrief.pay.practiceOnly': 'Practice only: no pay this time',
  'debrief.pay.none': 'No pay this time',
  'debrief.total': 'Total',
  'debrief.wallet': 'In your wallet: ¥{n}',
  'debrief.spent': 'You paid ¥{n}',
  'debrief.receipt': 'Receipt',
  'debrief.receiptThanks': 'ありがとうございました',
  'debrief.keepSub': 'Say each one from memory. Peeking keeps the card but no yen.',
  'debrief.friends': 'Friends',
  'debrief.apGain': '+{n} friendship points',
  'debrief.objective': 'Goal done',
  'debrief.dreamStep': 'Dream step done',
  'debrief.cultureOpen': 'Open the stamp book',
  'debrief.goOn': "Let's go",
  // the conversation screen
  'debrief.realTag': 'Real mode',
  'debrief.stuckReal': 'Stuck? Tap Hint, or type it in English and I will help.',
  'debrief.heard': 'I heard:',
  'debrief.yes': 'Yes',
  'debrief.edit': 'Edit',
  'debrief.tryAgain': 'Try again',
  'debrief.speechLow': "I couldn't hear that clearly. Try again, or type it.",
  'debrief.speechType': 'Voice is not catching it. Type it instead?',
  'debrief.over': 'Conversation over',
  'debrief.tryLater': "Let's talk again another time",
  'debrief.tryLaterSub': 'No pay this time and no penalty. Nothing is lost.',
  // notes in the feedback list
  'debrief.note': 'Note',
  'debrief.softSub': 'A note, not a mistake.',
  'debrief.maybeTitle': 'Maybe heard wrong',
  'debrief.maybeSub': 'The microphone was not sure about these lines, so they are only notes.',
} as const;

export const ar: Record<keyof typeof en, string> = {
  'debrief.stars': 'النجوم',
  'debrief.yenTitle': 'أجرك',
  'debrief.nudge': 'جرّب التالي بلا اقتراحات: نحو +¥{n}',
  'debrief.keep': 'احتفظ بهذه',
  'debrief.sayIt': 'قلها',
  'debrief.echoPaid': 'قلتها بنفسك: +¥{n}',
  'debrief.star1': 'أُنجزت كل الأهداف',
  'debrief.star2': 'معظمها بكلماتك ({pct}%+)',
  'debrief.star3': 'بكلماتك ({pct}%+) دون تلميحات وبطلبات مهذبة',
  'debrief.starsNone': 'أنجز كل الأهداف لتنال نجمة.',
  'debrief.pay.lines': 'جملك',
  'debrief.pay.steps': 'أُنجزت كل الخطوات',
  'debrief.pay.stepsLess': 'بعض الخطوات لم تُنجز',
  'debrief.pay.prepared': 'مستعد +{pct}%',
  'debrief.pay.real': 'الوضع الحقيقي +{pct}%',
  'debrief.pay.firstPhrase': 'أول مرة تقول هذه',
  'debrief.pay.star': 'النجمة {n}',
  'debrief.pay.repeat': 'لُعبت اليوم من قبل',
  'debrief.pay.softCap': 'المتاجر هادئة اليوم',
  'debrief.pay.practiceOnly': 'تدريب فقط: بلا أجر هذه المرة',
  'debrief.pay.none': 'بلا أجر هذه المرة',
  'debrief.total': 'المجموع',
  'debrief.wallet': 'في محفظتك: ¥{n}',
  'debrief.spent': 'دفعت ¥{n}',
  'debrief.receipt': 'الإيصال',
  'debrief.receiptThanks': 'ありがとうございました',
  'debrief.keepSub': 'قل كل جملة من الذاكرة. النظر إليها يحفظ البطاقة لكن بلا ين.',
  'debrief.friends': 'الأصدقاء',
  'debrief.apGain': '+{n} نقطة صداقة',
  'debrief.objective': 'أُنجز الهدف',
  'debrief.dreamStep': 'أُنجزت خطوة الحلم',
  'debrief.cultureOpen': 'افتح دفتر الأختام',
  'debrief.goOn': 'هيا بنا',
  'debrief.realTag': 'الوضع الحقيقي',
  'debrief.stuckReal': 'عالق؟ المس تلميح، أو اكتبها بالعربية وسأساعدك.',
  'debrief.heard': 'سمعتُ:',
  'debrief.yes': 'نعم',
  'debrief.edit': 'عدّل',
  'debrief.tryAgain': 'حاول مجددًا',
  'debrief.speechLow': 'لم أسمع بوضوح. حاول مجددًا أو اكتبها.',
  'debrief.speechType': 'الصوت لا يلتقط كلامك. هل تكتبها بدلًا من ذلك؟',
  'debrief.over': 'انتهت المحادثة',
  'debrief.tryLater': 'لنتحدث مرة أخرى في وقت آخر',
  'debrief.tryLaterSub': 'بلا أجر هذه المرة وبلا عقوبة. لم تخسر شيئًا.',
  'debrief.note': 'ملاحظة',
  'debrief.softSub': 'ملاحظة وليست خطأ.',
  'debrief.maybeTitle': 'ربما سُمعت خطأً',
  'debrief.maybeSub': 'لم يكن الميكروفون متأكدًا من هذه الجمل، لذا هي مجرد ملاحظات.',
};
