// UI strings for part-time shifts. Every key needs an English and an Arabic string; keys are prefixed 'jobs.'.
// Numbers (yen, counts) are inserted as Latin digits; the screen wraps them in dir="ltr" spans.

export const en = {
  'jobs.start': 'Start shift',
  'jobs.helping': 'Helping out',
  'jobs.showText': 'Show Japanese text (×0.7)',
  'jobs.showTrans': 'Show translation (×0.5)',
  'jobs.pay': 'You earned {n}',
  'jobs.rest': 'Enough for today. Come back tomorrow!',

  // intro and the job card
  'jobs.unavailable': 'This job is not open yet.',
  'jobs.introTitle': 'Tanaka-san wants a word',
  'jobs.introBody': 'Before your first shift, say hello to Tanaka-san at the register. It takes about two minutes.',
  'jobs.introGo': 'Talk to Tanaka-san',
  'jobs.rankLabel': 'Rank',
  'jobs.rank0': 'Trainee',
  'jobs.rank1': 'Full-fledged',
  'jobs.rank2': 'Veteran',
  'jobs.rank3': 'Ace',
  'jobs.rank4': 'Acting manager',
  'jobs.goodShifts': 'Good shifts: {n}',
  'jobs.nextRank': '{n} more good shifts to {rank}',
  'jobs.topRank': 'Top rank reached',
  'jobs.howItWorks': 'Five customers. Listen, take the order, say the total, say thanks. There is no timer.',
  'jobs.firstFree': 'Your first two shifts here have no text penalty: show the text whenever you need it.',
  'jobs.repeatNote': 'Second shift today: pay ×{m}.',
  'jobs.backToStreet': 'Back to the street',

  // playing
  'jobs.customerN': 'Customer {n} of {total}',
  'jobs.listen': 'Listen',
  'jobs.slow': 'Slowly',
  'jobs.cantListen': "Can't listen right now",
  'jobs.cantListenOn': 'Text is shown for the whole shift',
  'jobs.showTextFree': 'Show Japanese text',
  'jobs.showTransFree': 'Show translation',
  'jobs.hiddenLine': 'Listen to the customer, then take the order.',
  'jobs.greet': 'Say welcome',
  'jobs.greeted': 'Welcome said',
  'jobs.stepOrder': 'Order',
  'jobs.stepTotal': 'Total',
  'jobs.stepThanks': 'Thanks',
  'jobs.orderPrompt': 'Tap the items the customer asked for.',
  'jobs.heat': 'Heat it',
  'jobs.noBag': 'No bag',
  'jobs.cartEmpty': 'Nothing in the order yet',
  'jobs.add': 'Add {name}',
  'jobs.remove': 'Remove {name}',
  'jobs.confirmOrder': 'Confirm order',
  'jobs.totalPrompt': 'Tell the customer the total.',
  'jobs.changePrompt': 'They paid with a {paid} note. Tell them the change (お釣り).',
  'jobs.thanksPrompt': 'The order is done. Say your thanks to the customer.',
  'jobs.registerPaid': 'Total {total} · paid {paid}',
  'jobs.placeholderTotal': '320 or 三百二十円',
  'jobs.placeholderThanks': 'ありがとうございました',
  'jobs.say': 'Say it',
  'jobs.mic': 'Speak',
  'jobs.micListening': 'Listening…',
  'jobs.helpTiles': 'Build it from tiles',
  'jobs.helpPick': 'Choose from three',
  'jobs.helpNote': 'Help lowers the credit for this answer.',
  'jobs.tilesHint': 'Tap the pieces in order. Tap a placed piece to take it back.',
  'jobs.check': 'Check',
  'jobs.clear': 'Clear',
  'jobs.retryTyped': 'Not quite. Check the prices and try once more.',
  'jobs.right': 'Correct!',
  'jobs.wrong': 'Not quite.',
  'jobs.answerWas': 'It was',
  'jobs.orderWas': 'The order was',
  'jobs.nextCustomer': 'Next customer',
  'jobs.finish': 'Finish shift',
  'jobs.customerDone': 'Customer served',

  // leaving
  'jobs.quit': 'Leave shift',
  'jobs.quitTitle': 'Leave the shift?',
  'jobs.quitPaid': 'You served {n} customers, so you are paid {pay}. This shift will not count toward your goals or rank.',
  'jobs.quitNone': 'You have served fewer than 2 customers, so this shift pays nothing.',
  'jobs.keepWorking': 'Keep working',
  'jobs.leave': 'Leave',

  // result card
  'jobs.resultTitle': 'Shift complete',
  'jobs.resultQuit': 'Shift ended early',
  'jobs.accuracy': 'Accuracy',
  'jobs.served': 'Customers served',
  'jobs.assisted': 'Helped by text',
  'jobs.noPay': 'No pay this time.',
  'jobs.trial': 'Trial wage: this shift did not count toward your goals or rank.',
  'jobs.quitNoCount': 'This shift did not count toward your goals or rank.',
  'jobs.rankUp': 'Rank up: {rank}',
  'jobs.bonusItem': 'Perfect shift! A free rice ball is in your bag.',
  'jobs.counted': 'Good shift: it counts toward your goals and rank.',
  'jobs.saveWords': 'Words from this shift',
  'jobs.saveAll': 'Save these words',
  'jobs.saved': 'Saved to your words',
  'jobs.another': 'Another shift',
  'jobs.anotherMult': 'Another shift (pay ×{m})',
} as const;

export const ar: Record<keyof typeof en, string> = {
  'jobs.start': 'ابدأ الوردية',
  'jobs.helping': 'مساعدة',
  'jobs.showText': 'أظهر النص الياباني (×0.7)',
  'jobs.showTrans': 'أظهر الترجمة (×0.5)',
  'jobs.pay': 'ربحت {n}',
  'jobs.rest': 'يكفي لهذا اليوم. عُد غدًا!',

  'jobs.unavailable': 'هذا العمل غير متاح بعد.',
  'jobs.introTitle': 'السيد تاناكا يريد التحدث معك',
  'jobs.introBody': 'قبل ورديتك الأولى، قل مرحبًا للسيد تاناكا عند الصندوق. يستغرق ذلك نحو دقيقتين.',
  'jobs.introGo': 'تحدّث مع السيد تاناكا',
  'jobs.rankLabel': 'الرتبة',
  'jobs.rank0': 'متدرّب',
  'jobs.rank1': 'متمكّن',
  'jobs.rank2': 'محترف',
  'jobs.rank3': 'نجم',
  'jobs.rank4': 'نائب المدير',
  'jobs.goodShifts': 'ورديات جيدة: {n}',
  'jobs.nextRank': 'بقيت {n} ورديات جيدة للوصول إلى «{rank}»',
  'jobs.topRank': 'وصلت إلى أعلى رتبة',
  'jobs.howItWorks': 'خمسة زبائن. استمع، وخذ الطلب، وقل المجموع، ثم اشكر. لا يوجد مؤقّت.',
  'jobs.firstFree': 'ورديتاك الأوليان هنا بلا خصم على إظهار النص: أظهره متى احتجت إليه.',
  'jobs.repeatNote': 'الوردية الثانية اليوم: الأجر ×{m}.',
  'jobs.backToStreet': 'العودة إلى الشارع',

  'jobs.customerN': 'الزبون {n} من {total}',
  'jobs.listen': 'استمع',
  'jobs.slow': 'ببطء',
  'jobs.cantListen': 'لا أستطيع الاستماع الآن',
  'jobs.cantListenOn': 'النص ظاهر طوال الوردية',
  'jobs.showTextFree': 'أظهر النص الياباني',
  'jobs.showTransFree': 'أظهر الترجمة',
  'jobs.hiddenLine': 'استمع إلى الزبون ثم خذ الطلب.',
  'jobs.greet': 'قل أهلًا',
  'jobs.greeted': 'قلت أهلًا',
  'jobs.stepOrder': 'الطلب',
  'jobs.stepTotal': 'المجموع',
  'jobs.stepThanks': 'الشكر',
  'jobs.orderPrompt': 'اضغط على الأصناف التي طلبها الزبون.',
  'jobs.heat': 'تسخين',
  'jobs.noBag': 'بلا كيس',
  'jobs.cartEmpty': 'لا شيء في الطلب بعد',
  'jobs.add': 'أضف {name}',
  'jobs.remove': 'أزل {name}',
  'jobs.confirmOrder': 'أكّد الطلب',
  'jobs.totalPrompt': 'قل للزبون المجموع.',
  'jobs.changePrompt': 'دفع بورقة {paid}. قل له الباقي (お釣り).',
  'jobs.thanksPrompt': 'انتهى الطلب. اشكر الزبون.',
  'jobs.registerPaid': 'المجموع {total} · دفع {paid}',
  'jobs.placeholderTotal': '320 أو 三百二十円',
  'jobs.placeholderThanks': 'ありがとうございました',
  'jobs.say': 'قلها',
  'jobs.mic': 'تحدّث',
  'jobs.micListening': 'أستمع…',
  'jobs.helpTiles': 'ابنِها من القطع',
  'jobs.helpPick': 'اختر من ثلاثة',
  'jobs.helpNote': 'المساعدة تقلّل نقاط هذه الإجابة.',
  'jobs.tilesHint': 'اضغط على القطع بالترتيب. اضغط على قطعة موضوعة لإرجاعها.',
  'jobs.check': 'تحقّق',
  'jobs.clear': 'امسح',
  'jobs.retryTyped': 'ليس تمامًا. راجع الأسعار وحاول مرة أخرى.',
  'jobs.right': 'صحيح!',
  'jobs.wrong': 'ليس تمامًا.',
  'jobs.answerWas': 'كانت',
  'jobs.orderWas': 'كان الطلب',
  'jobs.nextCustomer': 'الزبون التالي',
  'jobs.finish': 'أنهِ الوردية',
  'jobs.customerDone': 'تمت خدمة الزبون',

  'jobs.quit': 'اترك الوردية',
  'jobs.quitTitle': 'هل تترك الوردية؟',
  'jobs.quitPaid': 'خدمت {n} زبائن، فستحصل على {pay}. لن تُحتسب هذه الوردية في أهدافك أو رتبتك.',
  'jobs.quitNone': 'خدمت أقل من زبونين، لذا لا أجر لهذه الوردية.',
  'jobs.keepWorking': 'تابع العمل',
  'jobs.leave': 'اترك',

  'jobs.resultTitle': 'انتهت الوردية',
  'jobs.resultQuit': 'انتهت الوردية مبكرًا',
  'jobs.accuracy': 'الدقة',
  'jobs.served': 'الزبائن الذين خدمتهم',
  'jobs.assisted': 'بمساعدة النص',
  'jobs.noPay': 'لا أجر هذه المرة.',
  'jobs.trial': 'أجر تجريبي: لم تُحتسب هذه الوردية في أهدافك أو رتبتك.',
  'jobs.quitNoCount': 'لم تُحتسب هذه الوردية في أهدافك أو رتبتك.',
  'jobs.rankUp': 'ترقية: {rank}',
  'jobs.bonusItem': 'وردية ممتازة! كرة أرز مجانية في حقيبتك.',
  'jobs.counted': 'وردية جيدة: تُحتسب في أهدافك ورتبتك.',
  'jobs.saveWords': 'كلمات من هذه الوردية',
  'jobs.saveAll': 'احفظ هذه الكلمات',
  'jobs.saved': 'حُفظت في كلماتك',
  'jobs.another': 'وردية أخرى',
  'jobs.anotherMult': 'وردية أخرى (الأجر ×{m})',
};
