// UI strings for the phone: Messages and Map pins. Every key needs an English and an Arabic string; keys are prefixed 'phone.'.

export const en = {
  'phone.title': 'Messages',
  'phone.voice': 'Voice message (tap to listen)',
  'phone.reveal': 'Show text',
  'phone.unread': '{n} new',
  'phone.tabs': 'Phone',
  'phone.tab.messages': 'Messages',
  'phone.tab.map': 'Map',
  'phone.chatSub': 'Text chat',
  'phone.needsPhone': 'Buy a phone at Hikari Denki to message your friends and see map pins.',
  'phone.needHearts': 'Messages start at ♥{n}',
  'phone.waiting': '{n} waiting',
  'phone.noneWaiting': 'No new messages',
  'phone.friendFrom': 'New message from {name}',
  'phone.reply': 'Reply',
  'phone.threadEmpty': '{name} has nothing new for you. A friend can send one new message a day, and there is no hurry.',
  'phone.threadLocked': 'Get to ♥{n} with {name} and their messages will start to arrive.',
  'phone.threadHint': 'Tap a word to see what it means. Reply in Japanese, or tap a suggestion.',
  'phone.plan': 'Plan today',
  'phone.back': 'Back to Messages',
  'phone.map.title': 'Map pins',
  'phone.map.goal': 'Your goal',
  'phone.map.friends': 'Friends',
  'phone.map.walk': 'Walk there',
  'phone.map.walkTo': 'Walk to {name}',
  'phone.map.none': 'No pins yet. Friends show up here once they live on the street.',
  'phone.place.park': 'The park',
  'phone.place.cafe': 'The café',
  'phone.place.konbini': 'The konbini',
  'phone.place.ramen': 'The ramen shop',
  'phone.place.station': 'The station',
  'phone.place.school': 'The school',
} as const;

export const ar: Record<keyof typeof en, string> = {
  'phone.title': 'الرسائل',
  'phone.voice': 'رسالة صوتية (اضغط للاستماع)',
  'phone.reveal': 'أظهر النص',
  'phone.unread': '{n} جديدة',
  'phone.tabs': 'الهاتف',
  'phone.tab.messages': 'الرسائل',
  'phone.tab.map': 'الخريطة',
  'phone.chatSub': 'محادثة نصية',
  'phone.needsPhone': 'اشترِ هاتفًا من متجر هيكاري دنكي لتراسل أصدقاءك وترى دبابيس الخريطة.',
  'phone.needHearts': 'تبدأ الرسائل عند ♥{n}',
  'phone.waiting': '{n} بانتظارك',
  'phone.noneWaiting': 'لا رسائل جديدة',
  'phone.friendFrom': 'رسالة جديدة من {name}',
  'phone.reply': 'ردّ',
  'phone.threadEmpty': 'ليس لدى {name} ما هو جديد لك. يمكن للصديق إرسال رسالة جديدة واحدة في اليوم، ولا داعي للعجلة.',
  'phone.threadLocked': 'عندما تصل إلى ♥{n} مع {name} ستبدأ رسائله بالوصول.',
  'phone.threadHint': 'اضغط على كلمة لترى معناها. ردّ باليابانية أو اضغط على اقتراح.',
  'phone.plan': 'موعد اليوم',
  'phone.back': 'العودة إلى الرسائل',
  'phone.map.title': 'دبابيس الخريطة',
  'phone.map.goal': 'هدفك',
  'phone.map.friends': 'الأصدقاء',
  'phone.map.walk': 'امشِ إلى هناك',
  'phone.map.walkTo': 'امشِ إلى {name}',
  'phone.map.none': 'لا دبابيس بعد. يظهر الأصدقاء هنا عندما يسكنون في الشارع.',
  'phone.place.park': 'الحديقة',
  'phone.place.cafe': 'المقهى',
  'phone.place.konbini': 'الكونبيني',
  'phone.place.ramen': 'مطعم الرامن',
  'phone.place.station': 'المحطة',
  'phone.place.school': 'المدرسة',
};
