// UI strings for the Prepare (Phrase Pocket) screen, the hidden-line Say it and the review/SRS additions. Every key needs an English and
// an Arabic string with the same {placeholders}; keys are prefixed 'prep.'.

export const en = {
  'prep.title': 'Get ready',
  'prep.skip': 'Skip (no +10% prepared bonus)',
  'prep.ready': "You're ready",
  'prep.mode.guided': 'Guided',
  'prep.mode.real': 'Real (no chips, +25%)',
  'prep.recall': 'Say it from memory',
  'prep.peek': 'Peek (no bonus for this line)',
  'prep.build': 'Build it from the pieces',

  'prep.progress': '{n} of {total}',
  'prep.mode': 'How do you want to play?',
  'prep.key': 'Key line',
  'prep.along': 'Say it along',
  'prep.test': 'Test yourself',
  'prep.finish': 'See results',
  'prep.start': 'Start talking',
  'prep.again': 'Practise again',
  'prep.review': 'Go over the lines anyway',
  'prep.empty': 'There is nothing to prepare for this one. You can just start talking.',
  'prep.ready.sub': 'Your lines are fresh: +10% prepared bonus is on.',
  'prep.ready.days': 'Good for {n} more days.',
  'prep.recall.sub': 'The Japanese is hidden. Say it, or type it in kana, kanji or romaji, or build it from the pieces.',
  'prep.done.ready': 'Well done. +10% prepared bonus on this conversation.',
  'prep.done.notYet.title': 'Nearly there',
  'prep.done.notYet': 'Say the key lines from memory to earn the +10% prepared bonus. You can try again or just start talking.',
  'prep.hidden': 'The line is hidden',
  'prep.replay': 'Hear it again',
  'prep.type.placeholder': 'Type it here',
  'prep.type.instead': 'Type it instead',
  'prep.check': 'Check',
  'prep.reset': 'Start over',
  'prep.right': 'Yes, that is it.',
  'prep.almost': 'Almost. Listen again and try once more, or peek.',
  'prep.peeked': 'Here it is. This line stays "studied" until you say it from memory.',
  'prep.build.hint': 'Tap the pieces in order. Some of them do not belong.',
  'prep.build.wrong': 'Not in that order yet. Tap a piece to take it back, or start over.',
  'prep.peek.echo': 'Peek (keeps the card, no yen)',
  'prep.status.new': 'New',
  'prep.status.seen': 'Studied',
  'prep.status.ready': 'Ready',
  'prep.pocket.title': 'Phrase pocket',
  'prep.pocket.open': 'Get ready',
  'prep.src.goal': 'A line you prepared',
  'prep.src.correction': 'A line to fix',
  'prep.src.prepare': 'From Get ready',
  'prep.src.echo': 'Said from memory',
  'prep.parked': 'held back for later',
  'prep.sprint.title': 'Quick sprint.',
  'prep.sprint.sub': 'A lot of cards are waiting. Here are {n} to start; the rest move forward with no penalty.',
  'prep.review.type': 'Type it (optional)',
  'prep.review.near': 'Not quite. Try again, or reveal the answer.',
} as const;

export const ar: Record<keyof typeof en, string> = {
  'prep.title': 'استعدّ',
  'prep.skip': 'تخطَّ (بلا مكافأة الاستعداد 10%)',
  'prep.ready': 'كل شيء جاهز',
  'prep.mode.guided': 'موجَّه',
  'prep.mode.real': 'حقيقي (بلا اقتراحات، +25%)',
  'prep.recall': 'قلها من الذاكرة',
  'prep.peek': 'ألقِ نظرة (بلا مكافأة لهذه الجملة)',
  'prep.build': 'ابنِها من القطع',

  'prep.progress': '{n} من {total}',
  'prep.mode': 'كيف تريد أن تلعب؟',
  'prep.key': 'جملة أساسية',
  'prep.along': 'قلها معي',
  'prep.test': 'اختبر نفسك',
  'prep.finish': 'عرض النتيجة',
  'prep.start': 'ابدأ الحديث',
  'prep.again': 'تدرّب مرة أخرى',
  'prep.review': 'راجع الجمل على أي حال',
  'prep.empty': 'لا يوجد ما تستعدّ له هنا. يمكنك أن تبدأ الحديث مباشرة.',
  'prep.ready.sub': 'جمَلك طازجة: مكافأة الاستعداد +10% مفعّلة.',
  'prep.ready.days': 'صالحة لـ {n} أيام أخرى.',
  'prep.recall.sub': 'الجملة اليابانية مخفية. قلها، أو اكتبها بالكانا أو الكانجي أو الروماجي، أو ركّبها من القطع.',
  'prep.done.ready': 'أحسنت. مكافأة الاستعداد +10% في هذه المحادثة.',
  'prep.done.notYet.title': 'اقتربت',
  'prep.done.notYet': 'قل الجمل الأساسية من الذاكرة لتنال مكافأة الاستعداد +10%. يمكنك المحاولة مجددًا أو بدء الحديث.',
  'prep.hidden': 'الجملة مخفية',
  'prep.replay': 'اسمعها مرة أخرى',
  'prep.type.placeholder': 'اكتبها هنا',
  'prep.type.instead': 'اكتبها بدلًا من ذلك',
  'prep.check': 'تحقّق',
  'prep.reset': 'ابدأ من جديد',
  'prep.right': 'نعم، هذه هي.',
  'prep.almost': 'تقريبًا. استمع مرة أخرى وحاول ثانية، أو ألقِ نظرة.',
  'prep.peeked': 'ها هي. تبقى هذه الجملة "مدروسة" حتى تقولها من الذاكرة.',
  'prep.build.hint': 'اضغط على القطع بالترتيب. بعضها لا ينتمي إلى الجملة.',
  'prep.build.wrong': 'ليس بهذا الترتيب بعد. اضغط على قطعة لإرجاعها، أو ابدأ من جديد.',
  'prep.peek.echo': 'ألقِ نظرة (تبقى البطاقة، بلا ين)',
  'prep.status.new': 'جديدة',
  'prep.status.seen': 'مدروسة',
  'prep.status.ready': 'جاهزة',
  'prep.pocket.title': 'جيب العبارات',
  'prep.pocket.open': 'استعدّ',
  'prep.src.goal': 'جملة حضّرتها',
  'prep.src.correction': 'جملة للتصحيح',
  'prep.src.prepare': 'من الاستعداد',
  'prep.src.echo': 'قيلت من الذاكرة',
  'prep.parked': 'مؤجّلة إلى وقت لاحق',
  'prep.sprint.title': 'جولة سريعة.',
  'prep.sprint.sub': 'هناك بطاقات كثيرة تنتظر. إليك {n} للبدء، والباقي يتأجّل دون أي عقوبة.',
  'prep.review.type': 'اكتبها (اختياري)',
  'prep.review.near': 'ليس تمامًا. حاول مرة أخرى أو اكشف الإجابة.',
};
