// UI strings for friends, phone chat, gifts and visiting. Every key needs an English and an Arabic string; keys are prefixed 'social.'.
// The Friends screen, the Friend card and the gift hand-over (agent 4A) own the keys from 'social.title' on; the ones above are the
// design's table (docs/GAME_DESIGN.md §7.6), used by the debrief and the interaction sheet. Arabic is written gender-neutral where the
// language allows (§8.5); numbers stay Latin digits and are wrapped in an LTR span by the screens.

export const en = {
  'social.hearts': 'Hearts',
  'social.next': 'Next at {n} hearts: {what}',
  'social.nextAt': 'Next at ♥{n}: {what}',
  'social.gift': 'Give a gift',
  'social.card': 'Friend card',
  'social.heartUp': '{name} likes you more now!',
  'social.notYet': 'Not yet',

  // ---- the Friends screen ----
  'social.title': 'Friends',
  'social.none': 'No friends here yet. Keep exploring!',
  'social.heartsOf': '{n} of 5 hearts',
  'social.ap': 'Affinity {n} / {max}',
  'social.apMax': 'Affinity {n}',
  'social.maxed': 'You are the closest of friends!',
  'social.more': 'Keep chatting to get closer.',
  'social.unmet': 'You have not met yet. Say hello {place}.',
  'social.at': 'You can find {name} {place}.',
  'social.place.park': 'at the park',
  'social.place.cafe': 'at the café',
  'social.place.konbini': 'at the konbini',
  'social.place.ramen': 'at the ramen shop',
  'social.place.station': 'at the station',
  'social.place.school': 'at the school',
  'social.u.name': 'greets you by name',
  'social.u.card': 'a Friend card',
  'social.u.smalltalk': 'small talk',
  'social.u.number': 'their phone number',
  'social.u.chat': 'phone chat',
  'social.u.casual': 'casual speech',
  'social.u.fact': 'something new about {name}',
  'social.facts': 'What I know about {name}',
  'social.factLocked': 'Learn at ♥{n}',
  'social.perks': 'Perks you have',
  'social.talk': 'Talk',
  'social.giftBtn': 'Gift',
  'social.message': 'Message',
  'social.talkDone': 'Hearts count once a day. You can still chat.',
  'social.eventReady': '{name} has something to tell you.',
  'social.listen': 'Listen',

  // ---- the gift hand-over ----
  'social.giftTitle': 'A gift for {name}',
  'social.giftPick': 'Choose something you bought.',
  'social.giftHow': 'You will say it in Japanese: the name of the gift and どうぞ.',
  'social.giftNone': 'You have nothing to give yet. Buy a present at the konbini first: chocolate, manga, a game card or a cake.',
  'social.giftGo': 'Hand it over',
  'social.noteDaily': 'You already gave {name} a gift today.',
  'social.noteNoTalk': 'Talk to {name} first today: a gift counts for twice as much.',
  'social.noteCapped': 'Nothing more to gain with {name} today.',
  'social.react.loved': '{name} loved your gift!',
  'social.react.liked': '{name} liked your gift.',
  'social.react.neutral': '{name} said thank you.',
  'social.react.disliked': '{name} was kind about it. Try something else next time.',
} as const;

export const ar: Record<keyof typeof en, string> = {
  'social.hearts': 'القلوب',
  'social.next': 'عند {n} قلوب: {what}',
  'social.nextAt': 'عند ♥{n}: {what}',
  'social.gift': 'قدّم هدية',
  'social.card': 'بطاقة الصديق',
  'social.heartUp': '{name} يحبك أكثر الآن!',
  'social.notYet': 'ليس بعد',

  'social.title': 'الأصدقاء',
  'social.none': 'لا أصدقاء هنا بعد. واصل الاستكشاف!',
  'social.heartsOf': '{n} من 5 قلوب',
  'social.ap': 'الألفة {n} / {max}',
  'social.apMax': 'الألفة {n}',
  'social.maxed': 'صداقتكما في أقصى درجات القرب!',
  'social.more': 'واصل الدردشة لتقترب أكثر.',
  'social.unmet': 'لم تلتقيا بعد. قل مرحبًا {place}.',
  'social.at': 'يمكنك أن تجد {name} {place}.',
  'social.place.park': 'في الحديقة',
  'social.place.cafe': 'في المقهى',
  'social.place.konbini': 'في الكونبيني',
  'social.place.ramen': 'في مطعم الرامن',
  'social.place.station': 'في المحطة',
  'social.place.school': 'في المدرسة',
  'social.u.name': 'يناديك باسمك',
  'social.u.card': 'بطاقة صديق',
  'social.u.smalltalk': 'دردشة قصيرة',
  'social.u.number': 'رقم هاتفه',
  'social.u.chat': 'محادثة عبر الهاتف',
  'social.u.casual': 'كلام عادي غير رسمي',
  'social.u.fact': 'شيء جديد عن {name}',
  'social.facts': 'ما أعرفه عن {name}',
  'social.factLocked': 'تعرفه عند ♥{n}',
  'social.perks': 'المزايا التي لديك',
  'social.talk': 'تحدّث',
  'social.giftBtn': 'هدية',
  'social.message': 'رسالة',
  'social.talkDone': 'تُحسب القلوب مرة في اليوم. ما زال بإمكانك الدردشة.',
  'social.eventReady': 'لدى {name} ما يقوله لك.',
  'social.listen': 'استمع',

  'social.giftTitle': 'هدية إلى {name}',
  'social.giftPick': 'اختر شيئًا اشتريته.',
  'social.giftHow': 'ستقولها باليابانية: اسم الهدية ثم \u2068どうぞ\u2069.',
  'social.giftNone': 'ليس لديك ما تقدّمه بعد. اشترِ هدية من الكونبيني أولًا: شوكولاتة أو مانغا أو بطاقة ألعاب أو كعكة.',
  'social.giftGo': 'سلّمها',
  'social.noteDaily': 'قدّمت هدية إلى {name} اليوم بالفعل.',
  'social.noteNoTalk': 'تحدّث مع {name} أولًا اليوم: فالهدية تساوي ضعف قيمتها حينها.',
  'social.noteCapped': 'لا مزيد من التقدّم مع {name} اليوم.',
  'social.react.loved': 'هديتك نالت إعجاب {name} كثيرًا!',
  'social.react.liked': 'هديتك أعجبت {name}.',
  'social.react.neutral': 'شكرًا من {name} على الهدية.',
  'social.react.disliked': 'جاء ردّ {name} لطيفًا. جرّب شيئًا آخر في المرة القادمة.',
};
