// UI strings for wallet, prices, shops and inventory. Every key needs an English and an Arabic string; keys are prefixed 'shop.', 'receipt.', 'wallet.' and, for the machine panels (VendingPanel, TicketPanel; agent 2G), 'panel.'.

export const en = {
  'shop.taxIncluded': 'tax included',
  'shop.notEnough': 'Not enough yen',
  'shop.closed': 'Not open yet',
  'shop.opensIn': 'Opens in Chapter {n}',
  'shop.someday': 'Someday (18+)',
  'shop.goods': 'Look at the goods',
  'shop.delivery': 'Delivery ¥{n}',
  'shop.owned': 'You have this',
  'shop.window': 'Look through the window',
  'receipt.subtotal': '小計 · Subtotal',
  'receipt.tax': '消費税 · Tax',
  'receipt.total': '合計 · Total',
  'receipt.paid': 'お預かり · Paid',
  'receipt.change': 'お釣り · Change',
  // ---- the machine panels ----
  'panel.cash': 'Cash',
  'panel.icLeft': 'On your card',
  'panel.vending.title': 'Vending machine',
  'panel.vending.pick': 'Choose a drink',
  'panel.vending.hot': 'Hot',
  'panel.vending.cold': 'Cold',
  'panel.vending.temp': 'Hot or cold?',
  'panel.vending.bought': 'You got {name}.',
  'panel.vending.another': 'Another drink',
  'panel.ticket.title': 'Ticket machine',
  'panel.ticket.ramenPick': 'Choose your ramen',
  'panel.ticket.extras': 'Extras (optional)',
  'panel.ticket.ramenGot': 'Your meal ticket',
  'panel.ticket.ramenHand': 'Hand it to the staff and tell them how you like your noodles.',
  'panel.ticket.ramenHave': 'You already have a meal ticket. Hand it to the staff first.',
  'panel.ticket.talk': 'Go to the counter',
  'panel.ticket.stationPick': 'Where are you going?',
  'panel.ticket.here': 'You are here',
  'panel.ticket.fareMap': 'Fare map',
  'panel.ticket.icFare': 'IC fare',
  'panel.ticket.paperFare': 'Paper ticket',
  'panel.ticket.stationGot': 'Your ticket to {name}',
  'panel.ticket.stationKeep': 'Keep it safe. You use it when you take the train.',
  'panel.ticket.stationHave': 'You already have a ticket to {name}.',
  'panel.ticket.icTapped': 'Tapped in with your IC card for {name}',
  'panel.ticket.icTip': 'With an IC card you can simply tap at the gate.',
  'panel.ticket.choose': 'Choose a place on the map',
  'panel.ticket.chooseRamen': 'Choose a bowl first',
  'panel.pay.coins': 'Coins',
  'panel.pay.insert': 'Insert coins',
  'panel.pay.inserted': 'Inserted',
  'panel.pay.needMore': '¥{n} more',
  'panel.pay.enough': 'Enough! Press the button.',
  'panel.pay.exact': 'Exact amount',
  'panel.pay.return': 'Return coins',
  'panel.pay.tapIc': 'Tap your IC card',
  'panel.pay.buy': 'Buy',
  'panel.pay.getTicket': 'Get my ticket',
  'panel.pay.coin': 'Coin',
  'panel.pay.note': 'Note',
  'panel.hint.earn': 'Talk with people in town to earn more yen.',
  'panel.hint.useIc': 'Your IC card has enough. Tap it instead.',
  'panel.hint.useCoins': 'Your cash is enough. Use coins instead.',
  'panel.hint.topUp': 'You can load your IC card at the station counter.',
  'panel.closed': 'This machine is out of order for now.',
  'panel.listen': 'Hear it',
} as const;

export const ar: Record<keyof typeof en, string> = {
  'shop.taxIncluded': 'شامل الضريبة',
  'shop.notEnough': 'الين لا يكفي',
  'shop.closed': 'لم يُفتح بعد',
  'shop.opensIn': 'يُفتح في الفصل {n}',
  'shop.someday': 'يومًا ما (18+)',
  'shop.goods': 'تفقّد البضائع',
  'shop.delivery': 'التوصيل ¥{n}',
  'shop.owned': 'لديك هذا',
  'shop.window': 'انظر عبر النافذة',
  'receipt.subtotal': '小計 · المجموع الفرعي',
  'receipt.tax': '消費税 · الضريبة',
  'receipt.total': '合計 · الإجمالي',
  'receipt.paid': 'お預かり · المدفوع',
  'receipt.change': 'お釣り · الباقي',
  // ---- the machine panels ----
  'panel.cash': 'النقد',
  'panel.icLeft': 'في بطاقتك',
  'panel.vending.title': 'آلة البيع',
  'panel.vending.pick': 'اختر مشروبًا',
  'panel.vending.hot': 'ساخن',
  'panel.vending.cold': 'بارد',
  'panel.vending.temp': 'ساخن أم بارد؟',
  'panel.vending.bought': 'حصلت على {name}.',
  'panel.vending.another': 'مشروب آخر',
  'panel.ticket.title': 'آلة التذاكر',
  'panel.ticket.ramenPick': 'اختر الرامن',
  'panel.ticket.extras': 'إضافات (اختياري)',
  'panel.ticket.ramenGot': 'تذكرة وجبتك',
  'panel.ticket.ramenHand': 'سلّمها للموظف وأخبره كيف تحب النودلز.',
  'panel.ticket.ramenHave': 'لديك تذكرة وجبة بالفعل. سلّمها للموظف أولًا.',
  'panel.ticket.talk': 'اذهب إلى المنضدة',
  'panel.ticket.stationPick': 'إلى أين تذهب؟',
  'panel.ticket.here': 'أنت هنا',
  'panel.ticket.fareMap': 'خريطة الأجرة',
  'panel.ticket.icFare': 'أجرة IC',
  'panel.ticket.paperFare': 'تذكرة ورقية',
  'panel.ticket.stationGot': 'تذكرتك إلى {name}',
  'panel.ticket.stationKeep': 'احتفظ بها. ستستخدمها عند ركوب القطار.',
  'panel.ticket.stationHave': 'لديك تذكرة إلى {name} بالفعل.',
  'panel.ticket.icTapped': 'مرّرت بطاقة IC إلى {name}',
  'panel.ticket.icTip': 'مع بطاقة IC يكفي أن تمرّرها عند البوابة.',
  'panel.ticket.choose': 'اختر مكانًا على الخريطة',
  'panel.ticket.chooseRamen': 'اختر طبق الرامن أولًا',
  'panel.pay.coins': 'عملات',
  'panel.pay.insert': 'أدخل العملات',
  'panel.pay.inserted': 'المُدخَل',
  'panel.pay.needMore': 'بقي ¥{n}',
  'panel.pay.enough': 'يكفي! اضغط الزر.',
  'panel.pay.exact': 'المبلغ بالضبط',
  'panel.pay.return': 'استرجع العملات',
  'panel.pay.tapIc': 'مرّر بطاقة IC',
  'panel.pay.buy': 'اشترِ',
  'panel.pay.getTicket': 'احصل على تذكرتي',
  'panel.pay.coin': 'عملة',
  'panel.pay.note': 'ورقة',
  'panel.hint.earn': 'تحدّث مع الناس في البلدة لتكسب مزيدًا من الين.',
  'panel.hint.useIc': 'رصيد بطاقة IC يكفي. مرّرها بدلًا من ذلك.',
  'panel.hint.useCoins': 'نقدك يكفي. استخدم العملات بدلًا من ذلك.',
  'panel.hint.topUp': 'يمكنك شحن بطاقة IC من شباك المحطة.',
  'panel.closed': 'هذه الآلة خارج الخدمة حاليًا.',
  'panel.listen': 'استمع إليها',
};
