import type { LexEntry } from '../types';
import { w, g } from './helpers';

// Lexicon entries for gifts and small talk (4B-a). Keep surfaces unique across the whole lexicon (the content tests report clashes).
export const SOCIAL_LEXICON: LexEntry[] = [
  // ---- gifts ----
  w('あげます', '', 'to give (I give you)', 'أعطي (أعطيك)'),
  g('どうしたの', 'what is it? (casual)', 'ما الأمر؟ (غير رسمي)'),
  g('どうしました', 'what is it? (polite)', 'ما الأمر؟ (رسمي)'),
  g('うーん', 'hmm', 'همم'),
  g('かな', 'I wonder / I think (casual)', 'أظن (غير رسمي)'),
  g('えっ', 'huh? / really?', 'ماذا؟ / حقًا؟'),
  g('ほんと', 'really (casual)', 'حقًا (غير رسمي)'),
  w('本当', 'ほんとう', 'really, true', 'حقًا، صحيح'),
  g('ございます', 'polite ending of ありがとう', 'نهاية مهذبة لكلمة شكرًا'),
  g('ございました', 'polite past ending of ありがとう', 'نهاية مهذبة في الماضي لكلمة شكرًا'),
  w('大切に', 'たいせつに', 'carefully, with care', 'بعناية'),
  w('大切', 'たいせつ', 'important, precious', 'مهم، عزيز'),
  w('毎日', 'まいにち', 'every day', 'كل يوم'),
  // ---- small talk: asking and answering ----
  w('最近', 'さいきん', 'lately', 'مؤخرًا'),
  w('使い', 'つかい', 'use (stem)', 'استخدام (جذر)'),
  w('やすい', '', 'easy to (do)', 'سهل (الفعل)'),
  g('る', 'plain ending of ている (ing)', 'نهاية غير رسمية لـ ている'),
  w('好きな', 'すきな', 'favourite, liked', 'مفضل'),
  w('食べ物', 'たべもの', 'food', 'طعام'),
  w('春', 'はる', 'spring', 'الربيع'),
  w('とる', '', 'to take (a photo)', 'يلتقط (صورة)'),
  w('とります', '', 'to take (a photo), polite', 'ألتقط (صورة)'),
  w('ひとり', '', 'one person, alone', 'وحيد، شخص واحد'),
  w('住んで', 'すんで', 'living (te-form)', 'يعيش (صيغة te)'),
  w('いろいろ', '', 'various, all kinds', 'متنوع، أنواع مختلفة'),
  w('聞きます', 'ききます', 'to listen, to hear', 'يستمع، يسمع'),
  w('聞こう', 'きこう', "let's listen (casual)", 'لنستمع (غير رسمي)'),
  w('聞きましょう', 'ききましょう', "let's listen", 'لنستمع'),
  w('一緒に', 'いっしょに', 'together', 'معًا'),
  w('日本', 'にほん', 'Japan', 'اليابان'),
  w('歌', 'うた', 'song', 'أغنية'),
  w('見る', 'みる', 'to see, to watch', 'يرى، يشاهد'),
  w('見ます', 'みます', 'to see, to watch (polite)', 'أشاهد'),
  w('見ません', 'みません', 'do not watch (polite)', 'لا أشاهد'),
  w('あまり', '', 'not very (with a negative)', 'ليس كثيرًا'),
  w('しません', '', 'do not do (polite)', 'لا أفعل'),
  w('しました', '', 'did (polite past)', 'فعلت'),
  w('行き', 'いき', 'go (stem)', 'اذهب (جذر)'),
  w('たい', '', 'want to (do)', 'يريد أن'),
  w('したい', '', 'want to do', 'يريد أن يفعل'),
  w('京都', 'きょうと', 'Kyoto', 'كيوتو'),
  w('天気', 'てんき', 'weather', 'الطقس'),
  g('だ', 'is (plain)', 'يكون (غير رسمي)'),
  w('がんばろう', '', "let's do our best (casual)", 'لنبذل جهدنا (غير رسمي)'),
  w('がんばりましょう', '', "let's do our best", 'لنبذل جهدنا'),
  w('週末', 'しゅうまつ', 'weekend', 'عطلة نهاية الأسبوع'),
  w('友だち', 'ともだち', 'friend', 'صديق'),
  w('会います', 'あいます', 'to meet (polite)', 'ألتقي'),
  w('何人', 'なんにん', 'how many people', 'كم شخصًا'),
  ...[
    w('ご家族', 'ごかぞく', "someone's family (polite)", 'عائلتك (مهذب)'),
    w('四人', 'よにん', 'four people', 'أربعة أشخاص'),
    w('三人', 'さんにん', 'three people', 'ثلاثة أشخاص'),
  ],
  g('なんだ', "(I see) it's like that (casual)", 'هكذا إذًا (غير رسمي)'),
  w('町', 'まち', 'town', 'بلدة'),
  w('きれい', '', 'pretty, clean', 'جميل، نظيف'),
  w('人', 'ひと', 'person, people', 'شخص، ناس'),
  w('多い', 'おおい', 'many', 'كثير'),
  w('服', 'ふく', 'clothes', 'ملابس'),
  w('毎週', 'まいしゅう', 'every week', 'كل أسبوع'),
  g('のが', 'the act of (+ が)', 'فعل كذا (+ が)'),
  g('のは', 'the act of (+ は)', 'فعل كذا (+ は)'),
  w('体', 'からだ', 'body', 'الجسم'),
  g('ん', 'explanatory ん (as in んだ)', 'ん التفسيرية'),
  g('んだ', 'explanatory ending (casual)', 'نهاية تفسيرية (غير رسمي)'),
  w('たくさん', '', 'a lot', 'كثيرًا'),
  w('明日', 'あした', 'tomorrow', 'غدًا'),
  g('またね', 'see you!', 'إلى اللقاء!'),
  // ---- friends' own words ----
  w('ギター', '', 'guitar', 'غيتار'),
  w('弾く', 'ひく', 'to play (a string instrument)', 'يعزف (آلة وترية)'),
  w('弾きます', 'ひきます', 'to play (a string instrument), polite', 'أعزف (آلة وترية)'),
  w('ねこ', '', 'cat', 'قطة'),
  w('名前', 'なまえ', 'name', 'اسم'),
  w('モカ', '', 'Mocha (the cat)', 'موكا (القطة)'),
  w('いつか', '', 'someday', 'يومًا ما'),
  w('ライブ', '', 'live show', 'حفل حي'),
  g('な', 'sentence-final softener (casual)', 'أداة ختام ليّنة (غير رسمي)'),
  w('かわいい', '', 'cute', 'لطيف'),
  w('毎晩', 'まいばん', 'every night', 'كل ليلة'),
  w('夜', 'よる', 'night', 'ليل'),
  w('眠い', 'ねむい', 'sleepy', 'نعسان'),
  w('会社', 'かいしゃ', 'company', 'شركة'),
  w('働き', 'はたらき', 'work (stem)', 'عمل (جذر)'),
  w('昨日', 'きのう', 'yesterday', 'أمس'),
  w('おれ', '', 'I (rough, male, casual)', 'أنا (خشن، للرجال، غير رسمي)'),
  w('スープ', '', 'soup, broth', 'حساء، مرق'),
  w('十二', 'じゅうに', 'twelve', 'اثنا عشر'),
  w('時間', 'じかん', 'hour, time', 'ساعة، وقت'),
  w('煮る', 'にる', 'to simmer', 'يغلي على نار هادئة'),
  w('煮ます', 'にます', 'to simmer (polite)', 'أغلي على نار هادئة'),
  w('うまい', '', 'tasty (rough)', 'لذيذ (خشن)'),
  g('だろ', "isn't it? (casual)", 'أليس كذلك؟ (غير رسمي)'),
  w('野球', 'やきゅう', 'baseball', 'بيسبول'),
  w('娘', 'むすめ', 'daughter', 'ابنة'),
  w('ひな', '', 'Hina (a name)', 'هينا (اسم)'),
  w('歳', 'さい', 'years old', 'سنة من العمر'),
  w('やって', '', 'doing (te-form of やる)', 'يفعل (صيغة te)'),
  w('作ります', 'つくります', 'to make (polite)', 'أصنع'),
  w('作る', 'つくる', 'to make', 'يصنع'),
  w('かけて', '', 'spending (time), te-form', 'يقضي (وقتًا)'),
  w('三十', 'さんじゅう', 'thirty', 'ثلاثون'),
  w('年', 'ねん', 'years', 'سنوات'),
  w('働いて', 'はたらいて', 'working (te-form)', 'يعمل (صيغة te)'),
  w('孫', 'まご', 'grandchild', 'حفيد'),
  w('大きい', 'おおきい', 'big', 'كبير'),
  w('面白い', 'おもしろい', 'interesting, funny', 'ممتع، مضحك'),
  w('教えます', 'おしえます', 'to teach (polite)', 'أعلّم'),
  w('書道', 'しょどう', 'calligraphy', 'الخط'),
  w('毎年', 'まいとし', 'every year', 'كل عام'),
  w('生徒', 'せいと', 'student, pupil', 'طالب، تلميذ'),
  w('読みます', 'よみます', 'to read (polite)', 'أقرأ'),
  w('字', 'じ', 'character, letter', 'حرف، رمز'),
  w('書く', 'かく', 'to write', 'يكتب'),
];
